import Foundation

// MARK: - MerconfigDocsRenderer
//
// Renders a parsed `MerConfigFile` (vocabulary + constants + instances +
// tools) as a static HTML reference page. The output is a single,
// self-contained file with inline CSS — no external assets, no JS — so a
// CI job can publish it as a build artefact and a developer can open it
// straight from disk.
//
// The renderer is pure: input → string. It deliberately lives in
// `MeridianCore` (not `MeridianCLI`) so other consumers (an IDE plugin's
// quick-look panel, an MCP server's `vocabulary/describe` response) can
// re-use it without depending on the CLI.

public struct MerconfigDocsRenderer {

    public struct Options: Sendable {
        public var pageTitle: String

        public init(pageTitle: String = "Meridian vocabulary") {
            self.pageTitle = pageTitle
        }

        public static let `default` = Options()
    }

    public let options: Options

    public init(options: Options = .default) {
        self.options = options
    }

    /// Render a single configuration file as a complete HTML document.
    public func render(_ config: MerConfigFile) -> String {
        let body = renderBody(config)
        return """
        <!doctype html>
        <html lang="en">
        <head>
          <meta charset="utf-8">
          <title>\(escape(options.pageTitle))</title>
          <style>\(stylesheet)</style>
        </head>
        <body>
          <header><h1>\(escape(options.pageTitle))</h1></header>
          <main>\(body)</main>
          <footer>Generated by <code>meridian docs</code>.</footer>
        </body>
        </html>
        """
    }

    /// Render multiple configs as a single HTML document, one labelled
    /// `<article>` per source file. Useful for projects that import
    /// several `.merconfig` files into one workflow.
    public func render(_ configs: [(name: String, config: MerConfigFile)]) -> String {
        let articles = configs.map { (name, config) in
            "<article class=\"vocab\"><h2>\(escape(name))</h2>\(renderBody(config))</article>"
        }.joined()
        return """
        <!doctype html>
        <html lang="en"><head><meta charset="utf-8"><title>\(escape(options.pageTitle))</title>
        <style>\(stylesheet)</style></head><body>
        <header><h1>\(escape(options.pageTitle))</h1></header>
        \(articles)
        </body></html>
        """
    }

    // MARK: - Section bodies

    /// Six sections: kinds, properties, phrases, constants, instances, tools.
    /// Properties live in their own section because the merconfig grammar
    /// declares them separately from the kind itself.
    private func renderBody(_ config: MerConfigFile) -> String {
        section("Kinds",       kindsTable(config))
            + section("Properties", propsTable(config))
            + section("Phrases",    phrasesTable(config))
            + section("Constants",  constantsTable(config))
            + section("Instances",  instancesTable(config))
            + section("Tools",      toolsTable(config))
    }

    private func kindsTable(_ config: MerConfigFile) -> String {
        let kinds: [KindDeclaration] = config.vocabulary.compactMap {
            if case .kind(let k) = $0 { return k } else { return nil }
        }
        if kinds.isEmpty { return emptyMessage }
        return "<dl>" + kinds.map { k in
            let parent = k.parent.isEmpty
                ? ""
                : " <em>(extends <code>\(escape(k.parent))</code>)</em>"
            return "<dt><code>\(escape(k.name))</code>\(parent)</dt>"
        }.joined() + "</dl>"
    }

    private func propsTable(_ config: MerConfigFile) -> String {
        let propDecls: [PropertyDeclaration] = config.vocabulary.compactMap {
            if case .property(let p) = $0 { return p } else { return nil }
        }
        if propDecls.isEmpty { return emptyMessage }
        return "<dl>" + propDecls.map { decl in
            let entries = decl.properties.map { entry in
                "<li><code>\(escape(entry.name))</code>: \(escape(propTypeText(entry.type)))</li>"
            }.joined()
            return "<dt>kind <code>\(escape(decl.kind))</code></dt><dd><ul>\(entries)</ul></dd>"
        }.joined() + "</dl>"
    }

    private func phrasesTable(_ config: MerConfigFile) -> String {
        let phrases: [PhraseDefinition] = config.vocabulary.compactMap {
            if case .phrase(let p) = $0 { return p } else { return nil }
        }
        if phrases.isEmpty { return emptyMessage }
        return "<dl>" + phrases.map { p in
            "<dt><code>\(escape(p.pattern.displayText))</code></dt>"
                + "<dd>\(p.workflowStructName.map { "workflow stub for <code>\(escape($0))</code>" } ?? "phrase")</dd>"
        }.joined() + "</dl>"
    }

    private func constantsTable(_ config: MerConfigFile) -> String {
        if config.constants.isEmpty { return emptyMessage }
        return "<dl>" + config.constants.map { c in
            "<dt><code>\(escape(c.name))</code></dt><dd>\(escape(literalText(c.value)))</dd>"
        }.joined() + "</dl>"
    }

    private func instancesTable(_ config: MerConfigFile) -> String {
        if config.instances.isEmpty { return emptyMessage }
        return "<dl>" + config.instances.map { inst in
            let props = inst.properties.map { (k, v) in
                "<li><code>\(escape(k))</code> = \(escape(propValueText(v)))</li>"
            }.joined()
            return "<dt><code>\(escape(inst.name))</code> <em>(\(escape(inst.kind)))</em></dt>"
                + "<dd><ul>\(props)</ul></dd>"
        }.joined() + "</dl>"
    }

    private func toolsTable(_ config: MerConfigFile) -> String {
        if config.tools.isEmpty { return emptyMessage }
        return "<dl>" + config.tools.map { t in
            let params = t.parameters.map { p in
                "<code>\(escape(p.name)): \(escape(p.type))</code>"
            }.joined(separator: ", ")
            return "<dt><code>\(escape(t.displayName))</code> <em>→ \(escape(t.returnType))</em></dt>"
                + "<dd>\(params.isEmpty ? "no params" : params)</dd>"
        }.joined() + "</dl>"
    }

    // MARK: - Stringifiers

    private func propTypeText(_ t: PropertyTypeAST) -> String {
        switch t {
        case .defaulted:                  return "<inferred>"
        case .explicit(let name):         return name
        case .enumeration(let cases, let defaultCase):
            let suffix = defaultCase.map { " (default: \($0))" } ?? ""
            return "enum {\(cases.joined(separator: ", "))}\(suffix)"
        }
    }

    private func literalText(_ l: LiteralAST) -> String {
        switch l {
        case .string(let s):      return "\"\(s)\""
        case .integer(let i):     return String(i)
        case .double(let d):      return String(d)
        case .boolean(let b):     return b ? "true" : "false"
        case .money(let v, let c): return "\(v) \(c)"
        case .duration(let v, _):  return "\(v) seconds"
        }
    }

    private func propValueText(_ v: PropertyValueAST) -> String {
        switch v {
        case .literal(let l): return literalText(l)
        case .envVar(let n):  return "$\(n)"
        }
    }

    // MARK: - Helpers

    private func section(_ heading: String, _ body: String) -> String {
        "<section><h2>\(escape(heading))</h2>\(body)</section>"
    }

    private var emptyMessage: String { "<p class=\"empty\">None.</p>" }

    private func escape(_ s: String) -> String {
        s
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }

    private let stylesheet = """
    body { font-family: -apple-system, system-ui, sans-serif; max-width: 56rem; margin: 2rem auto; padding: 0 1rem; color: #111; }
    header h1 { margin-bottom: .5rem; }
    section { margin: 1.5rem 0; padding-top: .25rem; border-top: 1px solid #eee; }
    section h2 { font-size: 1.25rem; margin: .75rem 0; }
    dt { margin-top: .75rem; }
    dd { margin: .15rem 0 .25rem 1.5rem; color: #333; }
    code { background: #f4f4f4; padding: .1em .3em; border-radius: 3px; }
    .empty { color: #888; font-style: italic; }
    .vocab { border: 1px solid #ddd; border-radius: 6px; padding: 1rem; margin: 1rem 0; }
    footer { color: #888; font-size: .875rem; margin-top: 3rem; }
    """
}
