// THIS FILE IS GENERATED BY MERIDIAN. DO NOT EDIT.
// Source: article_enrichment.meri
// Meridian IR version: 1.0

import Foundation
import MeridianRuntime

// B7: Runtime helper for {{ expr }} interpolation in fenced code blocks.
private func meridianStringify(_ v: Value) -> String {
    switch v {
    case .string(let s): return s
    case .number(let n): return "\(n)"
    case .boolean(let b): return b ? "true" : "false"
    case .null: return ""
    default: return v.description
    }
}

public enum ArticleEnrichment {

    // MARK: - Domain types

    public enum BrainUpgradeMode: String, Hashable, Codable, Sendable {
        case off, auto, notify
    }

    public enum JobState: String, Hashable, Codable, Sendable {
        case queued, running, succeeded, failed, cancelled, paused
    }

    public enum PageEnrichmentTier: String, Hashable, Codable, Sendable {
        case tier1, tier2, tier3
    }

    public enum PagePriority: String, Hashable, Codable, Sendable {
        case p0, p1, p2, p3
    }

    public enum QueryMode: String, Hashable, Codable, Sendable {
        case fast, deep, exhaustive
    }

    public enum SignalTier: String, Hashable, Codable, Sendable {
        case tier1, tier2, tier3
    }

    public enum VerdictStatus: String, Hashable, Codable, Sendable {
        case verified, partial, unverifiable, misattributed, retracted
    }

    public protocol PageKind: MeridianThing {
        var title: String { get }
        var slug: String { get }
        var body: String { get }
        var author: String { get }
        var priority: PagePriority { get }
        var enrichmentTier: PageEnrichmentTier { get }
    }

    public struct Page: PageKind {
        public var id: String
        public var title: String
        public var slug: String
        public var body: String
        public var author: String
        public var priority: PagePriority
        public var enrichmentTier: PageEnrichmentTier

        public init(
            id: String = "",
            title: String = "",
            slug: String = "",
            body: String = "",
            author: String = "",
            priority: PagePriority = .p0,
            enrichmentTier: PageEnrichmentTier = .tier1
        ) {
            self.id = id
            self.title = title
            self.slug = slug
            self.body = body
            self.author = author
            self.priority = priority
            self.enrichmentTier = enrichmentTier
        }
    }

    public protocol PersonKind: MeridianThing {
        var name: String { get }
        var headline: String { get }
        var email: String { get }
        var company: String { get }
    }

    public struct Person: PersonKind {
        public var id: String
        public var name: String
        public var headline: String
        public var email: String
        public var company: String

        public init(
            id: String = "",
            name: String = "",
            headline: String = "",
            email: String = "",
            company: String = ""
        ) {
            self.id = id
            self.name = name
            self.headline = headline
            self.email = email
            self.company = company
        }
    }

    public protocol CompanyKind: MeridianThing {
        var name: String { get }
        var domain: String { get }
        var description: String { get }
    }

    public struct Company: CompanyKind {
        public var id: String
        public var name: String
        public var domain: String
        public var description: String

        public init(
            id: String = "",
            name: String = "",
            domain: String = "",
            description: String = ""
        ) {
            self.id = id
            self.name = name
            self.domain = domain
            self.description = description
        }
    }

    public protocol MeetingKind: MeridianEvent {
        var title: String { get }
        var date: String { get }
        var transcript: String { get }
    }

    public struct Meeting: MeetingKind {
        public var id: String
        public var title: String
        public var date: String
        public var transcript: String

        public init(
            id: String = "",
            title: String = "",
            date: String = "",
            transcript: String = ""
        ) {
            self.id = id
            self.title = title
            self.date = date
            self.transcript = transcript
        }
    }

    public struct Concept: MeridianThing {
        public var id: String

        public init(
            id: String = ""
        ) {
            self.id = id
        }
    }

    public struct Idea: MeridianThing {
        public var id: String

        public init(
            id: String = ""
        ) {
            self.id = id
        }
    }

    public struct Original: MeridianArtifact {
        public var id: String

        public init(
            id: String = ""
        ) {
            self.id = id
        }
    }

    public struct Deal: MeridianThing {
        public var id: String

        public init(
            id: String = ""
        ) {
            self.id = id
        }
    }

    public struct Link: MeridianThing {
        public var id: String

        public init(
            id: String = ""
        ) {
            self.id = id
        }
    }

    public struct Source: MeridianThing {
        public var id: String

        public init(
            id: String = ""
        ) {
            self.id = id
        }
    }

    public struct TimelineEntry: MeridianEvent {
        public var id: String

        public init(
            id: String = ""
        ) {
            self.id = id
        }
    }

    public protocol ReportKind: MeridianArtifact {
        var title: String { get }
        var body: String { get }
    }

    public struct Report: ReportKind {
        public var id: String
        public var title: String
        public var body: String

        public init(
            id: String = "",
            title: String = "",
            body: String = ""
        ) {
            self.id = id
            self.title = title
            self.body = body
        }
    }

    public protocol JobKind: MeridianProcess {
        var status: String { get }
        var state: JobState { get }
    }

    public struct Job: JobKind {
        public var id: String
        public var status: String
        public var state: JobState

        public init(
            id: String = "",
            status: String = "",
            state: JobState = .queued
        ) {
            self.id = id
            self.status = status
            self.state = state
        }
    }

    public struct Task: MeridianProcess {
        public var id: String

        public init(
            id: String = ""
        ) {
            self.id = id
        }
    }

    public protocol SignalKind: MeridianSignal {
        var name: String { get }
        var phrasing: String { get }
        var tier: SignalTier { get }
    }

    public struct Signal: SignalKind {
        public var id: String
        public var name: String
        public var phrasing: String
        public var tier: SignalTier

        public init(
            id: String = "",
            name: String = "",
            phrasing: String = "",
            tier: SignalTier = .tier1
        ) {
            self.id = id
            self.name = name
            self.phrasing = phrasing
            self.tier = tier
        }
    }

    public struct Transcript: MeridianArtifact {
        public var id: String

        public init(
            id: String = ""
        ) {
            self.id = id
        }
    }

    public struct WebhookEvent: MeridianEvent {
        public var id: String

        public init(
            id: String = ""
        ) {
            self.id = id
        }
    }

    public struct SchemaPack: MeridianThing {
        public var id: String

        public init(
            id: String = ""
        ) {
            self.id = id
        }
    }

    public struct Recipe: MeridianThing {
        public var id: String

        public init(
            id: String = ""
        ) {
            self.id = id
        }
    }

    public protocol VerdictKind: MeridianVerdict {
        var status: VerdictStatus { get }
    }

    public struct Verdict: VerdictKind {
        public var id: String
        public var status: VerdictStatus

        public init(
            id: String = "",
            status: VerdictStatus = .verified
        ) {
            self.id = id
            self.status = status
        }
    }

    public protocol QueryKind: MeridianThing {
        var mode: QueryMode { get }
    }

    public struct Query: QueryKind {
        public var id: String
        public var mode: QueryMode

        public init(
            id: String = "",
            mode: QueryMode = .fast
        ) {
            self.id = id
            self.mode = mode
        }
    }

    public protocol BrainKind: MeridianSystem {
        var upgradeMode: BrainUpgradeMode { get }
    }

    public struct Brain: BrainKind {
        public var id: String
        public var upgradeMode: BrainUpgradeMode

        public init(
            id: String = "",
            upgradeMode: BrainUpgradeMode = .off
        ) {
            self.id = id
            self.upgradeMode = upgradeMode
        }
    }

    public protocol EntityKind: MeridianThing {
        var name: String { get }
        var type: String { get }
    }

    public struct Entity: EntityKind {
        public var id: String
        public var name: String
        public var type: String

        public init(
            id: String = "",
            name: String = "",
            type: String = ""
        ) {
            self.id = id
            self.name = name
            self.type = type
        }
    }

    public struct Attendee: PersonKind {
        public var id: String
        public var name: String
        public var headline: String
        public var email: String
        public var company: String

        public init(
            id: String = "",
            name: String = "",
            headline: String = "",
            email: String = "",
            company: String = ""
        ) {
            self.id = id
            self.name = name
            self.headline = headline
            self.email = email
            self.company = company
        }
    }

    public struct Input: MeridianThing {
        public var id: String

        public init(
            id: String = ""
        ) {
            self.id = id
        }
    }

    public struct Constants: Sendable {
        public let defaultEnrichmentTier: String = "tier2"
        public let defaultPriority: String = "p2"
        public let notabilityThreshold: Decimal = Decimal(20)
        public let enrichmentWindowInDays: Decimal = Decimal(7)
    }

    private static let constants = Constants()

    public struct ArticleEnrichmentInput: MeridianWorkflow {
        public let runtime: Runtime
        public let input: Input

        public static let skillMetadata: [String: String] = [
            "name": "article-enrichment",
            "version": "0.1.0",
            "description":
                "Transform raw article text dumps in the brain into structured pages with executive summary, verbatim quotes, key insights, why-it-matters, and cross-references. Replaces walls-of-text with quotable, actionable brain pages.",
            "triggers":
                "\"enrich this article\"\n\"enrich the article\"\n\"enriching the article\"\n\"enrich brain pages\"\n\"batch enrich\"\n\"enrich pass\"\n\"make brain pages useful\"",
            "mutating": "true",
            "writes_pages": "true",
            "writes_to": "media/articles/",
        ]

        public init(runtime: Runtime, input: Input) {
            self.runtime = runtime
            self.input = input
        }

        public func run() async throws -> WorkflowResult {
            var state = State()
            state.bind("input", input)
            let __meridianResumeContext = await runtime.consumeResumeContext()
            if let __meridianResumeContext {
                state.restore(from: __meridianResumeContext.restoredState)
            }
            var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
            func __meridianShouldRun(_ label: String) -> Bool {
                guard let target = __meridianResumeTarget else { return true }
                if target == label { __meridianResumeTarget = nil }
                return false
            }
            let constants = Constants()
            await runtime.workflowStarted(workflowName: "ArticleEnrichmentInput", parameters: [:])

            await runtime.complete(reason: nil)
            return WorkflowResult(
                reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(),
                bindings: state.snapshot().asValues)
        }
    }

    public struct WhenEnrichthisarticleFires: MeridianWorkflow {
        public let runtime: Runtime

        public init(runtime: Runtime) {
            self.runtime = runtime
        }

        public func run() async throws -> WorkflowResult {
            var state = State()
            let __meridianResumeContext = await runtime.consumeResumeContext()
            if let __meridianResumeContext {
                state.restore(from: __meridianResumeContext.restoredState)
            }
            var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
            func __meridianShouldRun(_ label: String) -> Bool {
                guard let target = __meridianResumeTarget else { return true }
                if target == label { __meridianResumeTarget = nil }
                return false
            }
            let constants = Constants()
            await runtime.workflowStarted(workflowName: "WhenEnrichthisarticleFires", parameters: [:])

            if __meridianShouldRun("progress:0.0:L1:C0") {
                // L1
                try await runtime.wait(.event("enrichThisArticle", matching: nil))
                try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
            }
            if __meridianShouldRun("progress:0.1:L1:C0") {
                // L1
                try await runtime.emit(
                    event: "trigger.enrichThisArticle.fired",
                    payload: [
                        "kind": .string("keyword"),
                        "spec": .string("enrich this article"),
                    ]
                )
                try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
            }

            await runtime.complete(reason: nil)
            return WorkflowResult(
                reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(),
                bindings: state.snapshot().asValues)
        }
    }

    public struct WhenEnricharticleFires: MeridianWorkflow {
        public let runtime: Runtime

        public init(runtime: Runtime) {
            self.runtime = runtime
        }

        public func run() async throws -> WorkflowResult {
            var state = State()
            let __meridianResumeContext = await runtime.consumeResumeContext()
            if let __meridianResumeContext {
                state.restore(from: __meridianResumeContext.restoredState)
            }
            var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
            func __meridianShouldRun(_ label: String) -> Bool {
                guard let target = __meridianResumeTarget else { return true }
                if target == label { __meridianResumeTarget = nil }
                return false
            }
            let constants = Constants()
            await runtime.workflowStarted(workflowName: "WhenEnricharticleFires", parameters: [:])

            if __meridianShouldRun("progress:0.0:L1:C0") {
                // L1
                try await runtime.wait(.event("enrichArticle", matching: nil))
                try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
            }
            if __meridianShouldRun("progress:0.1:L1:C0") {
                // L1
                try await runtime.emit(
                    event: "trigger.enrichArticle.fired",
                    payload: [
                        "kind": .string("keyword"),
                        "spec": .string("enrich the article"),
                    ]
                )
                try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
            }

            await runtime.complete(reason: nil)
            return WorkflowResult(
                reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(),
                bindings: state.snapshot().asValues)
        }
    }

    public struct WhenEnrichingarticleFires: MeridianWorkflow {
        public let runtime: Runtime

        public init(runtime: Runtime) {
            self.runtime = runtime
        }

        public func run() async throws -> WorkflowResult {
            var state = State()
            let __meridianResumeContext = await runtime.consumeResumeContext()
            if let __meridianResumeContext {
                state.restore(from: __meridianResumeContext.restoredState)
            }
            var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
            func __meridianShouldRun(_ label: String) -> Bool {
                guard let target = __meridianResumeTarget else { return true }
                if target == label { __meridianResumeTarget = nil }
                return false
            }
            let constants = Constants()
            await runtime.workflowStarted(workflowName: "WhenEnrichingarticleFires", parameters: [:])

            if __meridianShouldRun("progress:0.0:L1:C0") {
                // L1
                try await runtime.wait(.event("enrichingArticle", matching: nil))
                try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
            }
            if __meridianShouldRun("progress:0.1:L1:C0") {
                // L1
                try await runtime.emit(
                    event: "trigger.enrichingArticle.fired",
                    payload: [
                        "kind": .string("keyword"),
                        "spec": .string("enriching the article"),
                    ]
                )
                try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
            }

            await runtime.complete(reason: nil)
            return WorkflowResult(
                reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(),
                bindings: state.snapshot().asValues)
        }
    }

    public struct WhenEnrichbrainpagesFires: MeridianWorkflow {
        public let runtime: Runtime

        public init(runtime: Runtime) {
            self.runtime = runtime
        }

        public func run() async throws -> WorkflowResult {
            var state = State()
            let __meridianResumeContext = await runtime.consumeResumeContext()
            if let __meridianResumeContext {
                state.restore(from: __meridianResumeContext.restoredState)
            }
            var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
            func __meridianShouldRun(_ label: String) -> Bool {
                guard let target = __meridianResumeTarget else { return true }
                if target == label { __meridianResumeTarget = nil }
                return false
            }
            let constants = Constants()
            await runtime.workflowStarted(workflowName: "WhenEnrichbrainpagesFires", parameters: [:])

            if __meridianShouldRun("progress:0.0:L1:C0") {
                // L1
                try await runtime.wait(.event("enrichBrainPages", matching: nil))
                try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
            }
            if __meridianShouldRun("progress:0.1:L1:C0") {
                // L1
                try await runtime.emit(
                    event: "trigger.enrichBrainPages.fired",
                    payload: [
                        "kind": .string("keyword"),
                        "spec": .string("enrich brain pages"),
                    ]
                )
                try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
            }

            await runtime.complete(reason: nil)
            return WorkflowResult(
                reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(),
                bindings: state.snapshot().asValues)
        }
    }

    public struct WhenBatchenrichFires: MeridianWorkflow {
        public let runtime: Runtime

        public init(runtime: Runtime) {
            self.runtime = runtime
        }

        public func run() async throws -> WorkflowResult {
            var state = State()
            let __meridianResumeContext = await runtime.consumeResumeContext()
            if let __meridianResumeContext {
                state.restore(from: __meridianResumeContext.restoredState)
            }
            var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
            func __meridianShouldRun(_ label: String) -> Bool {
                guard let target = __meridianResumeTarget else { return true }
                if target == label { __meridianResumeTarget = nil }
                return false
            }
            let constants = Constants()
            await runtime.workflowStarted(workflowName: "WhenBatchenrichFires", parameters: [:])

            if __meridianShouldRun("progress:0.0:L1:C0") {
                // L1
                try await runtime.wait(.event("batchEnrich", matching: nil))
                try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
            }
            if __meridianShouldRun("progress:0.1:L1:C0") {
                // L1
                try await runtime.emit(
                    event: "trigger.batchEnrich.fired",
                    payload: [
                        "kind": .string("keyword"),
                        "spec": .string("batch enrich"),
                    ]
                )
                try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
            }

            await runtime.complete(reason: nil)
            return WorkflowResult(
                reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(),
                bindings: state.snapshot().asValues)
        }
    }

    public struct WhenEnrichpassFires: MeridianWorkflow {
        public let runtime: Runtime

        public init(runtime: Runtime) {
            self.runtime = runtime
        }

        public func run() async throws -> WorkflowResult {
            var state = State()
            let __meridianResumeContext = await runtime.consumeResumeContext()
            if let __meridianResumeContext {
                state.restore(from: __meridianResumeContext.restoredState)
            }
            var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
            func __meridianShouldRun(_ label: String) -> Bool {
                guard let target = __meridianResumeTarget else { return true }
                if target == label { __meridianResumeTarget = nil }
                return false
            }
            let constants = Constants()
            await runtime.workflowStarted(workflowName: "WhenEnrichpassFires", parameters: [:])

            if __meridianShouldRun("progress:0.0:L1:C0") {
                // L1
                try await runtime.wait(.event("enrichPass", matching: nil))
                try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
            }
            if __meridianShouldRun("progress:0.1:L1:C0") {
                // L1
                try await runtime.emit(
                    event: "trigger.enrichPass.fired",
                    payload: [
                        "kind": .string("keyword"),
                        "spec": .string("enrich pass"),
                    ]
                )
                try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
            }

            await runtime.complete(reason: nil)
            return WorkflowResult(
                reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(),
                bindings: state.snapshot().asValues)
        }
    }

    public struct WhenMakebrainpagesusefulFires: MeridianWorkflow {
        public let runtime: Runtime

        public init(runtime: Runtime) {
            self.runtime = runtime
        }

        public func run() async throws -> WorkflowResult {
            var state = State()
            let __meridianResumeContext = await runtime.consumeResumeContext()
            if let __meridianResumeContext {
                state.restore(from: __meridianResumeContext.restoredState)
            }
            var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
            func __meridianShouldRun(_ label: String) -> Bool {
                guard let target = __meridianResumeTarget else { return true }
                if target == label { __meridianResumeTarget = nil }
                return false
            }
            let constants = Constants()
            await runtime.workflowStarted(workflowName: "WhenMakebrainpagesusefulFires", parameters: [:])

            if __meridianShouldRun("progress:0.0:L1:C0") {
                // L1
                try await runtime.wait(.event("makeBrainPagesUseful", matching: nil))
                try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
            }
            if __meridianShouldRun("progress:0.1:L1:C0") {
                // L1
                try await runtime.emit(
                    event: "trigger.makeBrainPagesUseful.fired",
                    payload: [
                        "kind": .string("keyword"),
                        "spec": .string("make brain pages useful"),
                    ]
                )
                try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
            }

            await runtime.complete(reason: nil)
            return WorkflowResult(
                reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(),
                bindings: state.snapshot().asValues)
        }
    }

}
