// THIS FILE IS GENERATED BY MERIDIAN. DO NOT EDIT.
// Source: briefing.meri
// Meridian IR version: 1.0

import Foundation
import MeridianRuntime

// B7: Runtime helper for {{ expr }} interpolation in fenced code blocks.
private func meridianStringify(_ v: Value) -> String {
    switch v {
    case .string(let s): return s
    case .number(let n): return "\(n)"
    case .boolean(let b): return b ? "true" : "false"
    case .null: return ""
    default: return v.description
    }
}

// 1B: Shell-escape a value for safe interpolation inside a double-
// quoted span of a shell command (escapes \\, ", $, and backtick).
private func meridianShellQuote(_ v: Value) -> String {
    var out = ""
    for ch in meridianStringify(v) {
        if ch == "\\" || ch == "\"" || ch == "$" || ch == "`" { out.append("\\") }
        out.append(ch)
    }
    return out
}

// 1D: Output invariant — true iff the value's string form matches the
// regex pattern (anchored anywhere). An invalid pattern fails closed.
private func meridianRegexMatches(_ v: Value?, _ pattern: String) -> Bool {
    let s = v.map(meridianStringify) ?? ""
    guard let re = try? NSRegularExpression(pattern: pattern) else { return false }
    return re.firstMatch(in: s, range: NSRange(s.startIndex..., in: s)) != nil
}

private func meridianDef_Job_broken(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("state"), .string("failed"))
}

private func meridianDef_Job_finished(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("state"), .string("succeeded"))
}

private func meridianDef_Page_orphan(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.isEmpty(__subject.member("inboundLinks"))
}

private func meridianDef_Page_stale(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.isEmpty(__subject.member("compiledTruth"))
}

private func meridianDef_Page_unwritten(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.isEmpty(__subject.member("body"))
}

private func meridianDef_Page_urgent(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("priority"), .string("p0"))
}

public enum Briefing {

// MARK: - Domain types

public enum BrainUpgradeMode: String, Hashable, Codable, Sendable {
    case off, auto, notify
}

public enum JobState: String, Hashable, Codable, Sendable {
    case queued, running, succeeded, failed, cancelled, paused
}

public enum PageEnrichmentTier: String, Hashable, Codable, Sendable {
    case tier1, tier2, tier3
}

public enum PagePriority: String, Hashable, Codable, Sendable {
    case p0, p1, p2, p3
}

public enum QueryMode: String, Hashable, Codable, Sendable {
    case fast, deep, exhaustive
}

public enum SignalTier: String, Hashable, Codable, Sendable {
    case tier1, tier2, tier3
}

public enum VerdictStatus: String, Hashable, Codable, Sendable {
    case verified, partial, unverifiable, misattributed, retracted
}

public protocol PageKind: MeridianThing {
    var title: String { get }
    var slug: String { get }
    var body: String { get }
    var author: String { get }
    var compiledTruth: String { get }
    var links: [String] { get }
    var inboundLinks: [String] { get }
    var priority: PagePriority { get }
    var enrichmentTier: PageEnrichmentTier { get }
}

public struct Page: PageKind {
    public var id: String
    public var title: String
    public var slug: String
    public var body: String
    public var author: String
    public var compiledTruth: String
    public var links: [String]
    public var inboundLinks: [String]
    public var priority: PagePriority
    public var enrichmentTier: PageEnrichmentTier

    public init(
        id: String = "",
        title: String = "",
        slug: String = "",
        body: String = "",
        author: String = "",
        compiledTruth: String = "",
        links: [String] = [],
        inboundLinks: [String] = [],
        priority: PagePriority = .p0,
        enrichmentTier: PageEnrichmentTier = .tier1
    ) {
        self.id = id
        self.title = title
        self.slug = slug
        self.body = body
        self.author = author
        self.compiledTruth = compiledTruth
        self.links = links
        self.inboundLinks = inboundLinks
        self.priority = priority
        self.enrichmentTier = enrichmentTier
    }
}

public protocol PersonKind: MeridianThing {
    var name: String { get }
    var headline: String { get }
    var email: String { get }
    var company: String { get }
}

public struct Person: PersonKind {
    public var id: String
    public var name: String
    public var headline: String
    public var email: String
    public var company: String

    public init(
        id: String = "",
        name: String = "",
        headline: String = "",
        email: String = "",
        company: String = ""
    ) {
        self.id = id
        self.name = name
        self.headline = headline
        self.email = email
        self.company = company
    }
}

public protocol CompanyKind: MeridianThing {
    var name: String { get }
    var domain: String { get }
    var description: String { get }
}

public struct Company: CompanyKind {
    public var id: String
    public var name: String
    public var domain: String
    public var description: String

    public init(
        id: String = "",
        name: String = "",
        domain: String = "",
        description: String = ""
    ) {
        self.id = id
        self.name = name
        self.domain = domain
        self.description = description
    }
}

public protocol MeetingKind: MeridianEvent {
    var title: String { get }
    var date: String { get }
    var transcript: String { get }
}

public struct Meeting: MeetingKind {
    public var id: String
    public var title: String
    public var date: String
    public var transcript: String

    public init(
        id: String = "",
        title: String = "",
        date: String = "",
        transcript: String = ""
    ) {
        self.id = id
        self.title = title
        self.date = date
        self.transcript = transcript
    }
}

public struct Concept: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Idea: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Original: MeridianArtifact {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Deal: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Link: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Source: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct TimelineEntry: MeridianEvent {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol ReportKind: MeridianArtifact {
    var title: String { get }
    var body: String { get }
}

public struct Report: ReportKind {
    public var id: String
    public var title: String
    public var body: String

    public init(
        id: String = "",
        title: String = "",
        body: String = ""
    ) {
        self.id = id
        self.title = title
        self.body = body
    }
}

public protocol JobKind: MeridianProcess {
    var status: String { get }
    var state: JobState { get }
}

public struct Job: JobKind {
    public var id: String
    public var status: String
    public var state: JobState

    public init(
        id: String = "",
        status: String = "",
        state: JobState = .queued
    ) {
        self.id = id
        self.status = status
        self.state = state
    }
}

public struct Task: MeridianProcess {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol SignalKind: MeridianSignal {
    var name: String { get }
    var phrasing: String { get }
    var tier: SignalTier { get }
}

public struct Signal: SignalKind {
    public var id: String
    public var name: String
    public var phrasing: String
    public var tier: SignalTier

    public init(
        id: String = "",
        name: String = "",
        phrasing: String = "",
        tier: SignalTier = .tier1
    ) {
        self.id = id
        self.name = name
        self.phrasing = phrasing
        self.tier = tier
    }
}

public struct Transcript: MeridianArtifact {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct WebhookEvent: MeridianEvent {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct SchemaPack: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Recipe: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol VerdictKind: MeridianVerdict {
    var status: VerdictStatus { get }
}

public struct Verdict: VerdictKind {
    public var id: String
    public var status: VerdictStatus

    public init(
        id: String = "",
        status: VerdictStatus = .verified
    ) {
        self.id = id
        self.status = status
    }
}

public protocol QueryKind: MeridianThing {
    var mode: QueryMode { get }
}

public struct Query: QueryKind {
    public var id: String
    public var mode: QueryMode

    public init(
        id: String = "",
        mode: QueryMode = .fast
    ) {
        self.id = id
        self.mode = mode
    }
}

public protocol BrainKind: MeridianSystem {
    var upgradeMode: BrainUpgradeMode { get }
}

public struct Brain: BrainKind {
    public var id: String
    public var upgradeMode: BrainUpgradeMode

    public init(
        id: String = "",
        upgradeMode: BrainUpgradeMode = .off
    ) {
        self.id = id
        self.upgradeMode = upgradeMode
    }
}

public protocol EntityKind: MeridianThing {
    var name: String { get }
    var type: String { get }
    var links: [String] { get }
}

public struct Entity: EntityKind {
    public var id: String
    public var name: String
    public var type: String
    public var links: [String]

    public init(
        id: String = "",
        name: String = "",
        type: String = "",
        links: [String] = []
    ) {
        self.id = id
        self.name = name
        self.type = type
        self.links = links
    }
}

public struct Attendee: PersonKind {
    public var id: String
    public var name: String
    public var headline: String
    public var email: String
    public var company: String

    public init(
        id: String = "",
        name: String = "",
        headline: String = "",
        email: String = "",
        company: String = ""
    ) {
        self.id = id
        self.name = name
        self.headline = headline
        self.email = email
        self.company = company
    }
}

public struct Input: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol HealthReportKind: MeridianArtifact {
    var edgeCount: String { get }
    var timelineCount: String { get }
    var pageCount: String { get }
}

public struct HealthReport: HealthReportKind {
    public var id: String
    public var edgeCount: String
    public var timelineCount: String
    public var pageCount: String

    public init(
        id: String = "",
        edgeCount: String = "",
        timelineCount: String = "",
        pageCount: String = ""
    ) {
        self.id = id
        self.edgeCount = edgeCount
        self.timelineCount = timelineCount
        self.pageCount = pageCount
    }
}


public struct Constants: Sendable {
    public let defaultEnrichmentTier: String = "tier2"
    public let defaultPriority: String = "p2"
    public let notabilityThreshold: Decimal = Decimal(20)
    public let enrichmentWindowInDays: Decimal = Decimal(7)
}

private static let constants = Constants()

public struct BriefingInput: MeridianWorkflow {
    public let runtime: Runtime
    public let input: Input

    public static let skillMetadata: [String: String] = [
        "name": "briefing",
        "description": "Compile daily briefing with meeting context, active deals, and citation tracking",
        "triggers": "\"daily briefing\"\n\"morning briefing\"\n\"what's happening today\"",
        "mutating": "false",
    ]

    public init(runtime: Runtime, input: Input) {
        self.runtime = runtime
        self.input = input
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        state.bind("input", input)
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "BriefingInput", parameters: [:])

        if __meridianShouldRun("progress:0.0:L28:C0") {
            // L28
            _ = try await runtime.invoke(
                tool: "shell.run",
                args: [
                    "command": .string("gbrain recall --since-last-run --supersessions --pending --rollup --json"),
                ]
            )

            try await runtime.checkpoint(label: "progress:0.0:L28:C0", state: state.snapshot())
        }
        // L32
        let __meridianProseResults_L32 = try await runtime.executeProsePlan(
            prose: "compose the daily briefing\nFold the recall pulse into a \"Brain pulse\" section: contradictions resolved overnight, top mentions, new facts since the last briefing, and a pending-consolidation footer\nSummarize today's meetings with the participant context loaded below",
            snapshot: state.snapshot(),
            scopedTools: ["get_health", "get_page", "get_timeline", "list_pages", "query", "shell.run"]
        )
        for (__key, __value) in __meridianProseResults_L32 {
            state.bind(__key, __value)
        }
        // L42
        for (__meridianLoopIndex_0_2, attendee) in (state.get("attendees")?.asList ?? []).enumerated() {
            let __meridianLoopLabel_0_2 = "progress:0.2:iteration:\(__meridianLoopIndex_0_2)"
            if __meridianShouldRun(__meridianLoopLabel_0_2) {
            state.bind("attendee", attendee)
                if __meridianShouldRun("progress:0.2.body.0:L43:C0") {
                    // L43
                    // find their brain page
                    _ = try await runtime.invoke(
                        tool: "shell.run",
                        args: [
                            "command": .string("gbrain search \"" + meridianShellQuote(state.get("attendee.name") ?? .null) + "\""),
                        ]
                    )

                    try await runtime.checkpoint(label: "progress:0.2.body.0:L43:C0", state: state.snapshot())
                }
                if __meridianShouldRun("progress:0.2.body.1:L44:C0") {
                    // L44
                    // load compiled truth, recent timeline, relationship context
                    _ = try await runtime.invoke(
                        tool: "shell.run",
                        args: [
                            "command": .string("gbrain get " + meridianStringify(state.get("attendee.slug") ?? .null)),
                        ]
                    )

                    try await runtime.checkpoint(label: "progress:0.2.body.1:L44:C0", state: state.snapshot())
                }
                try await runtime.checkpoint(label: __meridianLoopLabel_0_2, state: state.snapshot())
            }
        }

        if __meridianShouldRun("progress:0.3:L49:C0") {
            // L49
            // deal pipeline snapshot
            _ = try await runtime.invoke(
                tool: "shell.run",
                args: [
                    "command": .string("gbrain query \"active deals status\""),
                ]
            )

            try await runtime.checkpoint(label: "progress:0.3:L49:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.4:L50:C0") {
            // L50
            // recent meeting pages with insights
            _ = try await runtime.invoke(
                tool: "shell.run",
                args: [
                    "command": .string("gbrain query \"meetings this week\""),
                ]
            )

            try await runtime.checkpoint(label: "progress:0.4:L50:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.5:L51:C0") {
            // L51
            // open threads and action items
            _ = try await runtime.invoke(
                tool: "shell.run",
                args: [
                    "command": .string("gbrain query \"pending commitments follow-ups\""),
                ]
            )

            try await runtime.checkpoint(label: "progress:0.5:L51:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.6:L52:C0") {
            // L52
            // people in play
            _ = try await runtime.invoke(
                tool: "shell.run",
                args: [
                    "command": .string("gbrain search --type person --sort updated --limit 10"),
                ]
            )

            try await runtime.checkpoint(label: "progress:0.6:L52:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.7:L64:C0") {
            // L64
            let pages = try await runtime.invoke(
                tool: "page.list",
                args: [
                    "filter": .string("today"),
                ]
            )
            state.bind("pages", pages)

            try await runtime.checkpoint(label: "progress:0.7:L64:C0", state: state.snapshot())
        }
        // L65
        state.bind("mine", Value.list(((state.get("pages"))?.asList ?? []).filter { __e in (MeridianComparison.identifies(__e.member("author"), state.get("input") ?? .null)) }))
        // L66
        if ((!(((state.get("pages"))?.asList ?? []).filter { __e in (meridianDef_Page_urgent(__e)) }).isEmpty)) || ((!(((state.get("pages"))?.asList ?? []).filter { __e in (meridianDef_Page_unwritten(__e)) }).isEmpty)) {
            if __meridianShouldRun("progress:0.9.then.0:L67:C0") {
                // L67
                try await runtime.emit(
                    event: "briefing.attention",
                    payload: [
                        "status": .string("needs review"),
                    ]
                )
                try await runtime.checkpoint(label: "progress:0.9.then.0:L67:C0", state: state.snapshot())
            }
        }

        if __meridianShouldRun("progress:0.10:L102:C0") {
            // L102
            let __relEntities = try await runtime.invoke(
                tool: "link.backlinks",
                args: [
                    "page": state.get("input") ?? .null,
                ]
            )
            state.bind("__relEntities", __relEntities)

            try await runtime.checkpoint(label: "progress:0.10:L102:C0", state: state.snapshot())
        }
        // L102
        state.bind("mentioned", Value.list(((state.get("__relEntities"))?.asList ?? [])))
        // L103
        for (__meridianLoopIndex_0_12, entity) in (state.get("mentioned")?.asList ?? []).enumerated() {
            let __meridianLoopLabel_0_12 = "progress:0.12:iteration:\(__meridianLoopIndex_0_12)"
            if __meridianShouldRun(__meridianLoopLabel_0_12) {
            state.bind("entity", entity)
                // L104
                if !(MeridianComparison.identifies(state.get("entity.links"), state.get("input"))) {
                    if __meridianShouldRun("progress:0.12.body.0.then.0:L133:C0") {
                        // L133
                        let link = try await runtime.invoke(
                            tool: "link.add",
                            args: [
                                "entity": state.get("entity") ?? .null,
                                "input": state.get("input") ?? .null,
                            ]
                        )
                        state.bind("link", link)

                        try await runtime.checkpoint(label: "progress:0.12.body.0.then.0:L133:C0", state: state.snapshot())
                    }
                }

                try await runtime.checkpoint(label: __meridianLoopLabel_0_12, state: state.snapshot())
            }
        }


        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenDailybriefingFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenDailybriefingFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("dailyBriefing", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.dailyBriefing.fired",
                payload: [
                    "kind": .string("schedule"),
                    "spec": .string("daily briefing"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenMorningbriefingFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenMorningbriefingFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("morningBriefing", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.morningBriefing.fired",
                payload: [
                    "kind": .string("schedule"),
                    "spec": .string("morning briefing"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenWhatshappeningtodayFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenWhatshappeningtodayFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("whatSHappeningToday", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.whatSHappeningToday.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("what's happening today"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

}