// THIS FILE IS GENERATED BY MERIDIAN. DO NOT EDIT.
// Source: citation_fixer.meri
// Meridian IR version: 1.0

import Foundation
import MeridianRuntime

// B7: Runtime helper for {{ expr }} interpolation in fenced code blocks.
private func meridianStringify(_ v: Value) -> String { v.scalarDescription }
private func meridianFormat(_ v: Value, as formatter: String) -> String {
    switch formatter.lowercased() {
    case "integer":
        if case .number(let n) = v { return NSDecimalNumber(decimal: n).intValue.description }
    case let f where f.hasPrefix("decimal(") && f.hasSuffix(")"):
        if case .number(let n) = v, let places = Int(f.dropFirst("decimal(".count).dropLast()) {
            let nf = NumberFormatter(); nf.minimumFractionDigits = places; nf.maximumFractionDigits = places
            return nf.string(from: NSDecimalNumber(decimal: n)) ?? n.description
        }
    case "short date", "long date":
        if case .date(let d) = v {
            let df = DateFormatter(); df.dateStyle = formatter.lowercased() == "short date" ? .short : .long; df.timeStyle = .none
            return df.string(from: d)
        }
    default: break
    }
    return meridianStringify(v)
}

// 1B: Shell-escape a value for safe interpolation inside a double-
// quoted span of a shell command (escapes \\, ", $, and backtick).
private func meridianShellQuote(_ v: Value) -> String {
    var out = ""
    for ch in meridianStringify(v) {
        if ch == "\\" || ch == "\"" || ch == "$" || ch == "`" { out.append("\\") }
        out.append(ch)
    }
    return out
}

// 1D: Output invariant — true iff the value's string form matches the
// regex pattern (anchored anywhere). An invalid pattern fails closed.
private func meridianRegexMatches(_ v: Value?, _ pattern: String) -> Bool {
    let s = v.map(meridianStringify) ?? ""
    guard let re = try? NSRegularExpression(pattern: pattern) else { return false }
    return re.firstMatch(in: s, range: NSRange(s.startIndex..., in: s)) != nil
}

private func meridianDef_Job_broken(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("state"), .string("failed"))
}

private func meridianDef_Job_finished(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("state"), .string("succeeded"))
}

private func meridianDef_Page_orphan(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.isEmpty(__subject.member("inboundLinks"))
}

private func meridianDef_Page_stale(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.isEmpty(__subject.member("compiledTruth"))
}

private func meridianDef_Page_unwritten(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.isEmpty(__subject.member("body"))
}

private func meridianDef_Page_urgent(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("priority"), .string("p0"))
}

public enum CitationFixer {

// MARK: - Domain types

public enum BrainUpgradeMode: String, Hashable, Codable, Sendable {
    case off, auto, notify
}

public enum JobState: String, Hashable, Codable, Sendable {
    case queued, running, succeeded, failed, cancelled, paused
}

public enum PageEnrichmentTier: String, Hashable, Codable, Sendable {
    case tier1, tier2, tier3
}

public enum PagePriority: String, Hashable, Codable, Sendable {
    case p0, p1, p2, p3
}

public enum QueryMode: String, Hashable, Codable, Sendable {
    case fast, deep, exhaustive
}

public enum SignalTier: String, Hashable, Codable, Sendable {
    case tier1, tier2, tier3
}

public enum VerdictStatus: String, Hashable, Codable, Sendable {
    case verified, partial, unverifiable, misattributed, retracted
}

public protocol PageKind: MeridianThing {
    var title: String { get }
    var slug: String { get }
    var body: String { get }
    var author: String { get }
    var compiledTruth: String { get }
    var links: [String] { get }
    var inboundLinks: [String] { get }
    var priority: PagePriority { get }
    var enrichmentTier: PageEnrichmentTier { get }
}

public struct Page: PageKind {
    public var id: String
    public var title: String
    public var slug: String
    public var body: String
    public var author: String
    public var compiledTruth: String
    public var links: [String]
    public var inboundLinks: [String]
    public var priority: PagePriority
    public var enrichmentTier: PageEnrichmentTier

    public init(
        id: String = "",
        title: String = "",
        slug: String = "",
        body: String = "",
        author: String = "",
        compiledTruth: String = "",
        links: [String] = [],
        inboundLinks: [String] = [],
        priority: PagePriority = .p0,
        enrichmentTier: PageEnrichmentTier = .tier1
    ) {
        self.id = id
        self.title = title
        self.slug = slug
        self.body = body
        self.author = author
        self.compiledTruth = compiledTruth
        self.links = links
        self.inboundLinks = inboundLinks
        self.priority = priority
        self.enrichmentTier = enrichmentTier
    }
}

public protocol PersonKind: MeridianThing {
    var name: String { get }
    var headline: String { get }
    var email: String { get }
    var company: String { get }
}

public struct Person: PersonKind {
    public var id: String
    public var name: String
    public var headline: String
    public var email: String
    public var company: String

    public init(
        id: String = "",
        name: String = "",
        headline: String = "",
        email: String = "",
        company: String = ""
    ) {
        self.id = id
        self.name = name
        self.headline = headline
        self.email = email
        self.company = company
    }
}

public protocol CompanyKind: MeridianThing {
    var name: String { get }
    var domain: String { get }
    var description: String { get }
}

public struct Company: CompanyKind {
    public var id: String
    public var name: String
    public var domain: String
    public var description: String

    public init(
        id: String = "",
        name: String = "",
        domain: String = "",
        description: String = ""
    ) {
        self.id = id
        self.name = name
        self.domain = domain
        self.description = description
    }
}

public protocol MeetingKind: MeridianEvent {
    var title: String { get }
    var date: String { get }
    var transcript: String { get }
}

public struct Meeting: MeetingKind {
    public var id: String
    public var title: String
    public var date: String
    public var transcript: String

    public init(
        id: String = "",
        title: String = "",
        date: String = "",
        transcript: String = ""
    ) {
        self.id = id
        self.title = title
        self.date = date
        self.transcript = transcript
    }
}

public struct Concept: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Idea: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Original: MeridianArtifact {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Deal: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Link: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Source: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct TimelineEntry: MeridianEvent {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol ReportKind: MeridianArtifact {
    var title: String { get }
    var body: String { get }
}

public struct Report: ReportKind {
    public var id: String
    public var title: String
    public var body: String

    public init(
        id: String = "",
        title: String = "",
        body: String = ""
    ) {
        self.id = id
        self.title = title
        self.body = body
    }
}

public protocol JobKind: MeridianProcess {
    var status: String { get }
    var state: JobState { get }
}

public struct Job: JobKind {
    public var id: String
    public var status: String
    public var state: JobState

    public init(
        id: String = "",
        status: String = "",
        state: JobState = .queued
    ) {
        self.id = id
        self.status = status
        self.state = state
    }
}

public struct Task: MeridianProcess {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol SignalKind: MeridianSignal {
    var name: String { get }
    var phrasing: String { get }
    var tier: SignalTier { get }
}

public struct Signal: SignalKind {
    public var id: String
    public var name: String
    public var phrasing: String
    public var tier: SignalTier

    public init(
        id: String = "",
        name: String = "",
        phrasing: String = "",
        tier: SignalTier = .tier1
    ) {
        self.id = id
        self.name = name
        self.phrasing = phrasing
        self.tier = tier
    }
}

public struct Transcript: MeridianArtifact {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct WebhookEvent: MeridianEvent {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct SchemaPack: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Recipe: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol VerdictKind: MeridianVerdict {
    var status: VerdictStatus { get }
}

public struct Verdict: VerdictKind {
    public var id: String
    public var status: VerdictStatus

    public init(
        id: String = "",
        status: VerdictStatus = .verified
    ) {
        self.id = id
        self.status = status
    }
}

public protocol QueryKind: MeridianThing {
    var mode: QueryMode { get }
}

public struct Query: QueryKind {
    public var id: String
    public var mode: QueryMode

    public init(
        id: String = "",
        mode: QueryMode = .fast
    ) {
        self.id = id
        self.mode = mode
    }
}

public protocol BrainKind: MeridianSystem {
    var upgradeMode: BrainUpgradeMode { get }
}

public struct Brain: BrainKind {
    public var id: String
    public var upgradeMode: BrainUpgradeMode

    public init(
        id: String = "",
        upgradeMode: BrainUpgradeMode = .off
    ) {
        self.id = id
        self.upgradeMode = upgradeMode
    }
}

public protocol EntityKind: MeridianThing {
    var name: String { get }
    var type: String { get }
    var links: [String] { get }
}

public struct Entity: EntityKind {
    public var id: String
    public var name: String
    public var type: String
    public var links: [String]

    public init(
        id: String = "",
        name: String = "",
        type: String = "",
        links: [String] = []
    ) {
        self.id = id
        self.name = name
        self.type = type
        self.links = links
    }
}

public struct Attendee: PersonKind {
    public var id: String
    public var name: String
    public var headline: String
    public var email: String
    public var company: String

    public init(
        id: String = "",
        name: String = "",
        headline: String = "",
        email: String = "",
        company: String = ""
    ) {
        self.id = id
        self.name = name
        self.headline = headline
        self.email = email
        self.company = company
    }
}

public struct Input: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol HealthReportKind: MeridianArtifact {
    var edgeCount: String { get }
    var timelineCount: String { get }
    var pageCount: String { get }
}

public struct HealthReport: HealthReportKind {
    public var id: String
    public var edgeCount: String
    public var timelineCount: String
    public var pageCount: String

    public init(
        id: String = "",
        edgeCount: String = "",
        timelineCount: String = "",
        pageCount: String = ""
    ) {
        self.id = id
        self.edgeCount = edgeCount
        self.timelineCount = timelineCount
        self.pageCount = pageCount
    }
}


public struct Constants: Sendable {
    public let defaultEnrichmentTier: String = "tier2"
    public let defaultPriority: String = "p2"
    public let notabilityThreshold: Decimal = Decimal(20)
    public let enrichmentWindowInDays: Decimal = Decimal(7)
}

private static let constants = Constants()

public struct CitationFixerInput: MeridianWorkflow {
    public let runtime: Runtime
    public let input: Input

    public static let skillMetadata: [String: String] = [
        "name": "citation-fixer",
        "version": "1.1.0",
        "description": "Audit and fix citation formatting across brain pages. Ensures every fact has\nan inline [Source: ...] citation matching the standard format. Extended in\nv0.25.1: scans for broken tweet/post references that lack actual URLs and\nresolves them via the host's X / Twitter API integration.",
        "triggers": "\"fix citations\"\n\"fix broken citations\"\n\"citation audit\"\n\"check citations\"\n\"citation fixer\"",
        "tools": "search\nget_page\nput_page\nlist_pages",
        "mutating": "true",
    ]

    public init(runtime: Runtime, input: Input) {
        self.runtime = runtime
        self.input = input
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        state.bind("input", input)
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "CitationFixerInput", parameters: [:])

        // L36
        let __meridianProseResults_L36 = try await runtime.executeAutonomousLoop(
            prose: "Ensure every acceptance criterion below holds, taking corrective action until all of them are satisfied:\n- Every brain page is scanned for citation compliance\n- Missing citations are flagged with specific location\n- Malformed citations are fixed to match the standard format\n- **(v0.25.1)** Tweet / post references without URLs are resolved via X API and patched with deterministic `https://x.com/<handle>/status/<id>` links.\n- Results reported with counts (scanned, fixed, remaining)",
            snapshot: state.snapshot(),
            scopedTools: ["page.get", "page.list", "page.search", "publish", "shell.run"],
            maxSteps: 32,
            replanAfterFailures: 3
        )
        for (__key, __value) in __meridianProseResults_L36 {
            state.bind(__key, __value)
        }
        // L46
        let __meridianProseResults_L46 = try await runtime.executeProsePlan(
            prose: "scan pages and repair their citations\nList pages and read each one, checking for inline [Source: ...] citations\nIdentify facts without a citation, citations missing a date or source type, and citations with the wrong format\nRewrite malformed citations to match the quality convention\nResolve tweet references via the X API integration\nReport counts of pages scanned, citations found, issues fixed, and remaining gaps",
            snapshot: state.snapshot(),
            scopedTools: ["page.get", "page.list", "page.search", "publish", "shell.run"]
        )
        for (__key, __value) in __meridianProseResults_L46 {
            state.bind(__key, __value)
        }
        if __meridianShouldRun("progress:0.2:L126:C0") {
            // L126
            _ = try await runtime.invoke(
                tool: "shell.run",
                args: [
                    "command": .string("for f in $(find . -name \"*.md\" -not -path \"./node_modules/*\"); do"),
                ]
            )

            try await runtime.checkpoint(label: "progress:0.2:L126:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.3:L126:C0") {
            // L126
            _ = try await runtime.invoke(
                tool: "shell.run",
                args: [
                    "command": .string("refs=$(grep -ci \"tweet\\|posted\\|x post\\|RT\\|retweet\\|said on X\" \"$f\")"),
                ]
            )

            try await runtime.checkpoint(label: "progress:0.3:L126:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.4:L126:C0") {
            // L126
            _ = try await runtime.invoke(
                tool: "shell.run",
                args: [
                    "command": .string("links=$(grep -c \"x.com/.*/status/\" \"$f\")"),
                ]
            )

            try await runtime.checkpoint(label: "progress:0.4:L126:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.5:L126:C0") {
            // L126
            _ = try await runtime.invoke(
                tool: "shell.run",
                args: [
                    "command": .string("if [ \"$refs\" -gt 2 ] && [ \"$links\" -eq 0 ]; then"),
                ]
            )

            try await runtime.checkpoint(label: "progress:0.5:L126:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.6:L126:C0") {
            // L126
            _ = try await runtime.invoke(
                tool: "shell.run",
                args: [
                    "command": .string("echo \"$f\""),
                ]
            )

            try await runtime.checkpoint(label: "progress:0.6:L126:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.7:L126:C0") {
            // L126
            _ = try await runtime.invoke(
                tool: "shell.run",
                args: [
                    "command": .string("fi"),
                ]
            )

            try await runtime.checkpoint(label: "progress:0.7:L126:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.8:L126:C0") {
            // L126
            _ = try await runtime.invoke(
                tool: "shell.run",
                args: [
                    "command": .string("done"),
                ]
            )

            try await runtime.checkpoint(label: "progress:0.8:L126:C0", state: state.snapshot())
        }
        // L167
        let __meridianProseResults_L167 = try await runtime.executeAutonomousLoop(
            prose: "Ensure every acceptance criterion below holds, taking corrective action until all of them are satisfied:\n- ❌ Inventing citations for facts that have no source. Flag them\n- ❌ Removing facts that lack citations (flag them; don't delete)\n- ❌ Fixing citations without reading the full page context\n- ❌ Batch-fixing without checking quality on a sample first (see `conventions/test-before-bulk.md`).\n- ❌ Composing tweet URLs by guessing the tweet id. Always go through the X API; deterministic links only.",
            snapshot: state.snapshot(),
            scopedTools: ["page.get", "page.list", "page.search", "publish", "shell.run"],
            maxSteps: 32,
            replanAfterFailures: 3
        )
        for (__key, __value) in __meridianProseResults_L167 {
            state.bind(__key, __value)
        }
        // L186
        let __meridianProseResults_L186 = try await runtime.executeProsePlan(
            prose: "follow the Metrics guidance\nIf running as a recurring batch, track state in a small JSON file under\n`~/.gbrain/citation-fixer-state.json`:\ncodeblock:json:ewogICJsYXN0X3J1biI6ICIyMDI2LTA0LTE1VC4uLiIsCiAgInBhZ2VzX3NjYW5uZWQiOiAwLAogICJjaXRhdGlvbnNfZml4ZWQiOiAwLAogICJ0d2VldF9saW5rc19yZXNvbHZlZCI6IDAsCiAgImNpdGF0aW9uc191bnJlc29sdmFibGUiOiAwLAogICJwYWdlc19yZW1haW5pbmciOiAxNDI0Cn0=",
            snapshot: state.snapshot(),
            scopedTools: ["page.get", "page.list", "page.search", "publish", "shell.run"]
        )
        for (__key, __value) in __meridianProseResults_L186 {
            state.bind(__key, __value)
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenFixcitationsFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenFixcitationsFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("fixCitations", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.fixCitations.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("fix citations"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenFixbrokencitationsFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenFixbrokencitationsFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("fixBrokenCitations", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.fixBrokenCitations.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("fix broken citations"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenCitationauditFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenCitationauditFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("citationAudit", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.citationAudit.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("citation audit"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenCheckcitationsFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenCheckcitationsFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("checkCitations", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.checkCitations.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("check citations"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenCitationfixerFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenCitationfixerFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("citationFixer", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.citationFixer.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("citation fixer"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

}