// THIS FILE IS GENERATED BY MERIDIAN. DO NOT EDIT.
// Source: cron_scheduler.meri
// Meridian IR version: 1.0

import Foundation
import MeridianRuntime

// B7: Runtime helper for {{ expr }} interpolation in fenced code blocks.
private func meridianStringify(_ v: Value) -> String { v.scalarDescription }
private func meridianFormat(_ v: Value, as formatter: String) -> String {
    switch formatter.lowercased() {
    case "integer":
        if case .number(let n) = v { return NSDecimalNumber(decimal: n).intValue.description }
    case let f where f.hasPrefix("decimal(") && f.hasSuffix(")"):
        if case .number(let n) = v, let places = Int(f.dropFirst("decimal(".count).dropLast()) {
            let nf = NumberFormatter(); nf.minimumFractionDigits = places; nf.maximumFractionDigits = places
            return nf.string(from: NSDecimalNumber(decimal: n)) ?? n.description
        }
    case "short date", "long date":
        if case .date(let d) = v {
            let df = DateFormatter(); df.dateStyle = formatter.lowercased() == "short date" ? .short : .long; df.timeStyle = .none
            return df.string(from: d)
        }
    default: break
    }
    return meridianStringify(v)
}

// 1B: Shell-escape a value for safe interpolation inside a double-
// quoted span of a shell command (escapes \\, ", $, and backtick).
private func meridianShellQuote(_ v: Value) -> String {
    var out = ""
    for ch in meridianStringify(v) {
        if ch == "\\" || ch == "\"" || ch == "$" || ch == "`" { out.append("\\") }
        out.append(ch)
    }
    return out
}

// 1D: Output invariant — true iff the value's string form matches the
// regex pattern (anchored anywhere). An invalid pattern fails closed.
private func meridianRegexMatches(_ v: Value?, _ pattern: String) -> Bool {
    let s = v.map(meridianStringify) ?? ""
    guard let re = try? NSRegularExpression(pattern: pattern) else { return false }
    return re.firstMatch(in: s, range: NSRange(s.startIndex..., in: s)) != nil
}

private func meridianDef_Job_broken(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("state"), .string("failed"))
}

private func meridianDef_Job_finished(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("state"), .string("succeeded"))
}

private func meridianDef_Page_orphan(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.isEmpty(__subject.member("inboundLinks"))
}

private func meridianDef_Page_stale(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.isEmpty(__subject.member("compiledTruth"))
}

private func meridianDef_Page_unwritten(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.isEmpty(__subject.member("body"))
}

private func meridianDef_Page_urgent(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("priority"), .string("p0"))
}

public enum CronScheduler {

// MARK: - Domain types

public enum BrainUpgradeMode: String, Hashable, Codable, Sendable {
    case off, auto, notify
}

public enum JobState: String, Hashable, Codable, Sendable {
    case queued, running, succeeded, failed, cancelled, paused
}

public enum PageEnrichmentTier: String, Hashable, Codable, Sendable {
    case tier1, tier2, tier3
}

public enum PagePriority: String, Hashable, Codable, Sendable {
    case p0, p1, p2, p3
}

public enum QueryMode: String, Hashable, Codable, Sendable {
    case fast, deep, exhaustive
}

public enum SignalTier: String, Hashable, Codable, Sendable {
    case tier1, tier2, tier3
}

public enum VerdictStatus: String, Hashable, Codable, Sendable {
    case verified, partial, unverifiable, misattributed, retracted
}

public protocol PageKind: MeridianThing {
    var title: String { get }
    var slug: String { get }
    var body: String { get }
    var author: String { get }
    var compiledTruth: String { get }
    var links: [String] { get }
    var inboundLinks: [String] { get }
    var priority: PagePriority { get }
    var enrichmentTier: PageEnrichmentTier { get }
}

public struct Page: PageKind {
    public var id: String
    public var title: String
    public var slug: String
    public var body: String
    public var author: String
    public var compiledTruth: String
    public var links: [String]
    public var inboundLinks: [String]
    public var priority: PagePriority
    public var enrichmentTier: PageEnrichmentTier

    public init(
        id: String = "",
        title: String = "",
        slug: String = "",
        body: String = "",
        author: String = "",
        compiledTruth: String = "",
        links: [String] = [],
        inboundLinks: [String] = [],
        priority: PagePriority = .p0,
        enrichmentTier: PageEnrichmentTier = .tier1
    ) {
        self.id = id
        self.title = title
        self.slug = slug
        self.body = body
        self.author = author
        self.compiledTruth = compiledTruth
        self.links = links
        self.inboundLinks = inboundLinks
        self.priority = priority
        self.enrichmentTier = enrichmentTier
    }
}

public protocol PersonKind: MeridianThing {
    var name: String { get }
    var headline: String { get }
    var email: String { get }
    var company: String { get }
}

public struct Person: PersonKind {
    public var id: String
    public var name: String
    public var headline: String
    public var email: String
    public var company: String

    public init(
        id: String = "",
        name: String = "",
        headline: String = "",
        email: String = "",
        company: String = ""
    ) {
        self.id = id
        self.name = name
        self.headline = headline
        self.email = email
        self.company = company
    }
}

public protocol CompanyKind: MeridianThing {
    var name: String { get }
    var domain: String { get }
    var description: String { get }
}

public struct Company: CompanyKind {
    public var id: String
    public var name: String
    public var domain: String
    public var description: String

    public init(
        id: String = "",
        name: String = "",
        domain: String = "",
        description: String = ""
    ) {
        self.id = id
        self.name = name
        self.domain = domain
        self.description = description
    }
}

public protocol MeetingKind: MeridianEvent {
    var title: String { get }
    var date: String { get }
    var transcript: String { get }
}

public struct Meeting: MeetingKind {
    public var id: String
    public var title: String
    public var date: String
    public var transcript: String

    public init(
        id: String = "",
        title: String = "",
        date: String = "",
        transcript: String = ""
    ) {
        self.id = id
        self.title = title
        self.date = date
        self.transcript = transcript
    }
}

public struct Concept: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Idea: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Original: MeridianArtifact {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Deal: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Link: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Source: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct TimelineEntry: MeridianEvent {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol ReportKind: MeridianArtifact {
    var title: String { get }
    var body: String { get }
}

public struct Report: ReportKind {
    public var id: String
    public var title: String
    public var body: String

    public init(
        id: String = "",
        title: String = "",
        body: String = ""
    ) {
        self.id = id
        self.title = title
        self.body = body
    }
}

public protocol JobKind: MeridianProcess {
    var status: String { get }
    var state: JobState { get }
}

public struct Job: JobKind {
    public var id: String
    public var status: String
    public var state: JobState

    public init(
        id: String = "",
        status: String = "",
        state: JobState = .queued
    ) {
        self.id = id
        self.status = status
        self.state = state
    }
}

public struct Task: MeridianProcess {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol SignalKind: MeridianSignal {
    var name: String { get }
    var phrasing: String { get }
    var tier: SignalTier { get }
}

public struct Signal: SignalKind {
    public var id: String
    public var name: String
    public var phrasing: String
    public var tier: SignalTier

    public init(
        id: String = "",
        name: String = "",
        phrasing: String = "",
        tier: SignalTier = .tier1
    ) {
        self.id = id
        self.name = name
        self.phrasing = phrasing
        self.tier = tier
    }
}

public struct Transcript: MeridianArtifact {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct WebhookEvent: MeridianEvent {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct SchemaPack: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Recipe: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol VerdictKind: MeridianVerdict {
    var status: VerdictStatus { get }
}

public struct Verdict: VerdictKind {
    public var id: String
    public var status: VerdictStatus

    public init(
        id: String = "",
        status: VerdictStatus = .verified
    ) {
        self.id = id
        self.status = status
    }
}

public protocol QueryKind: MeridianThing {
    var mode: QueryMode { get }
}

public struct Query: QueryKind {
    public var id: String
    public var mode: QueryMode

    public init(
        id: String = "",
        mode: QueryMode = .fast
    ) {
        self.id = id
        self.mode = mode
    }
}

public protocol BrainKind: MeridianSystem {
    var upgradeMode: BrainUpgradeMode { get }
}

public struct Brain: BrainKind {
    public var id: String
    public var upgradeMode: BrainUpgradeMode

    public init(
        id: String = "",
        upgradeMode: BrainUpgradeMode = .off
    ) {
        self.id = id
        self.upgradeMode = upgradeMode
    }
}

public protocol EntityKind: MeridianThing {
    var name: String { get }
    var type: String { get }
    var links: [String] { get }
}

public struct Entity: EntityKind {
    public var id: String
    public var name: String
    public var type: String
    public var links: [String]

    public init(
        id: String = "",
        name: String = "",
        type: String = "",
        links: [String] = []
    ) {
        self.id = id
        self.name = name
        self.type = type
        self.links = links
    }
}

public struct Attendee: PersonKind {
    public var id: String
    public var name: String
    public var headline: String
    public var email: String
    public var company: String

    public init(
        id: String = "",
        name: String = "",
        headline: String = "",
        email: String = "",
        company: String = ""
    ) {
        self.id = id
        self.name = name
        self.headline = headline
        self.email = email
        self.company = company
    }
}

public struct Input: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol HealthReportKind: MeridianArtifact {
    var edgeCount: String { get }
    var timelineCount: String { get }
    var pageCount: String { get }
}

public struct HealthReport: HealthReportKind {
    public var id: String
    public var edgeCount: String
    public var timelineCount: String
    public var pageCount: String

    public init(
        id: String = "",
        edgeCount: String = "",
        timelineCount: String = "",
        pageCount: String = ""
    ) {
        self.id = id
        self.edgeCount = edgeCount
        self.timelineCount = timelineCount
        self.pageCount = pageCount
    }
}


public struct Constants: Sendable {
    public let defaultEnrichmentTier: String = "tier2"
    public let defaultPriority: String = "p2"
    public let notabilityThreshold: Decimal = Decimal(20)
    public let enrichmentWindowInDays: Decimal = Decimal(7)
}

private static let constants = Constants()

public struct CronSchedulerInput: MeridianWorkflow {
    public let runtime: Runtime
    public let input: Input

    public static let skillMetadata: [String: String] = [
        "name": "cron-scheduler",
        "version": "1.0.0",
        "description": "Schedule management with staggering, quiet hours, and wake-up override.\nValidates schedules, prevents collisions, and gates delivery during quiet hours.",
        "triggers": "\"schedule a job\"\n\"cron\"\n\"quiet hours\"\n\"what jobs are running\"",
        "tools": "search\nget_page\nput_page",
        "mutating": "true",
    ]

    public init(runtime: Runtime, input: Input) {
        self.runtime = runtime
        self.input = input
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        state.bind("input", input)
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "CronSchedulerInput", parameters: [:])

        // L27
        let __meridianProseResults_L27 = try await runtime.executeAutonomousLoop(
            prose: "Ensure every acceptance criterion below holds, taking corrective action until all of them are satisfied:\n- Schedule staggering: max 1 job per 5-minute slot, no collisions\n- Quiet hours gating: timezone-aware, with user-awake override\n- Thin job prompts: jobs say \"Read skills/X/SKILL.md and run it\" (no inline 3000-word prompts)\n- Idempotency: jobs can run twice without duplicate side effects\n- Results saved as reports: `reports/{job-name}/{YYYY-MM-DD-HHMM}.md`",
            snapshot: state.snapshot(),
            scopedTools: ["page.get", "page.search", "publish", "shell.run"],
            maxSteps: 32,
            replanAfterFailures: 3
        )
        for (__key, __value) in __meridianProseResults_L27 {
            state.bind(__key, __value)
        }
        // L35
        let __meridianProseResults_L35 = try await runtime.executeProsePlan(
            prose: "schedule a cron job\nDefine the job name, cron schedule, skill to run, and timeout\nValidate the schedule against existing jobs using the five-minute offset rule and suggest the next free slot on collision\nCheck quiet hours (default 11 PM to 8 AM) and hold output during quiet hours\nRegister the entry with the host scheduler, executing via Minions rather than a direct agent turn\nWrite a thin one-line job prompt that reads and runs the target skill",
            snapshot: state.snapshot(),
            scopedTools: ["page.get", "page.search", "publish", "shell.run"]
        )
        for (__key, __value) in __meridianProseResults_L35 {
            state.bind(__key, __value)
        }
        // L55
        let __meridianProseResults_L55 = try await runtime.executeProsePlan(
            prose: "follow the multi-source sync guidance\nWhen the brain has 2+ active sources (anything `gbrain sources list` shows with a non-null `local_path` that isn't archived), use one consolidated cron line instead of N per-source entries\n**Preferred (multi-source)**:\ncodeblock:cron:Ki81ICogKiAqICogZ2JyYWluIHN5bmMgLS1hbGwgLS1wYXJhbGxlbCA0IC0td29ya2VycyA0IC0tc2tpcC1mYWlsZWQ=\nThis replaces N per-source lines AND auto-picks-up future sources without\na crontab edit. Concurrency budget: `parallel × workers × 2 ≈ 32`\nconnections during the wave (each per-file worker opens its own\n2-connection pool). Stay under your Postgres `max_connections` setting\n**Avoid (legacy)**: separate `gbrain sync --source default` and\n`gbrain sync --source zion-brain` entries staggered by 5 minutes. They\nrequire manual deconfliction every time a new source is added, and a\nslow source can race a fast source on the legacy global `gbrain-sync`\nlock (v0.40.3.0+ uses per-source `gbrain-sync:<sourceId>` locks but the\nper-source cron pattern doesn't benefit from the parallelism that\n`--all --parallel` actually delivers)\n`gbrain doctor` surfaces the recommended line as a `sync_consolidation`\ncheck whenever it detects 2+ active sources. Paste-ready from there\nchecklist:ai-autonomy:U2NoZWR1bGluZyBqb2JzIGF0IHRoZSBzYW1lIG1pbnV0ZSAoOjAwIGZvciBldmVyeXRoaW5nKQpJbmxpbmUgMzAwMC13b3JkIHByb21wdHMgaW4gY3JvbiBqb2JzICh1c2Ugc2tpbGwgZmlsZSByZWZlcmVuY2VzKQpSdW5uaW5nIGNyb24gam9icyB3aXRob3V0IHRlc3Rpbmcgb24gMy01IGl0ZW1zIGZpcnN0CkpvYnMgdGhhdCBwcm9kdWNlIGRpZmZlcmVudCBvdXRwdXQgb24gcmUtcnVuIChub3QgaWRlbXBvdGVudCkKU2VuZGluZyBub3RpZmljYXRpb25zIGR1cmluZyBxdWlldCBob3VycyAoc2F2ZSB0byBoZWxkIHF1ZXVlIGluc3RlYWQpClNlcGFyYXRlIHBlci1zb3VyY2UgYGdicmFpbiBzeW5jIC0tc291cmNlIDxpZD5gIGNyb24gZW50cmllcyB3aGVuIGBnYnJhaW4gc3luYyAtLWFsbCAtLXBhcmFsbGVsIE4gLS13b3JrZXJzIE5gIHdvdWxkIHJlcGxhY2UgdGhlbSB3aXRoIG9uZSBsaW5lIHRoYXQgYXV0by1waWNrcy11cCBmdXR1cmUgc291cmNlcy4=",
            snapshot: state.snapshot(),
            scopedTools: ["page.get", "page.search", "publish", "shell.run"]
        )
        for (__key, __value) in __meridianProseResults_L55 {
            state.bind(__key, __value)
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenSchedulejobFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenSchedulejobFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("scheduleJob", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.scheduleJob.fired",
                payload: [
                    "kind": .string("schedule"),
                    "spec": .string("schedule a job"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenCronFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenCronFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("cron", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.cron.fired",
                payload: [
                    "kind": .string("schedule"),
                    "spec": .string("cron"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenQuiethoursFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenQuiethoursFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("quietHours", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.quietHours.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("quiet hours"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenWhatjobsarerunningFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenWhatjobsarerunningFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("whatJobsAreRunning", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.whatJobsAreRunning.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("what jobs are running"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

}