// THIS FILE IS GENERATED BY MERIDIAN. DO NOT EDIT.
// Source: ingest.meri
// Meridian IR version: 1.0

import Foundation
import MeridianRuntime

// B7: Runtime helper for {{ expr }} interpolation in fenced code blocks.
private func meridianStringify(_ v: Value) -> String {
    switch v {
    case .string(let s): return s
    case .number(let n): return "\(n)"
    case .boolean(let b): return b ? "true" : "false"
    case .null: return ""
    default: return v.description
    }
}

// 1B: Shell-escape a value for safe interpolation inside a double-
// quoted span of a shell command (escapes \\, ", $, and backtick).
private func meridianShellQuote(_ v: Value) -> String {
    var out = ""
    for ch in meridianStringify(v) {
        if ch == "\\" || ch == "\"" || ch == "$" || ch == "`" { out.append("\\") }
        out.append(ch)
    }
    return out
}

// 1D: Output invariant — true iff the value's string form matches the
// regex pattern (anchored anywhere). An invalid pattern fails closed.
private func meridianRegexMatches(_ v: Value?, _ pattern: String) -> Bool {
    let s = v.map(meridianStringify) ?? ""
    guard let re = try? NSRegularExpression(pattern: pattern) else { return false }
    return re.firstMatch(in: s, range: NSRange(s.startIndex..., in: s)) != nil
}

private func meridianDef_Job_broken(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("state"), .string("failed"))
}

private func meridianDef_Job_finished(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("state"), .string("succeeded"))
}

private func meridianDef_Page_unwritten(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.isEmpty(__subject.member("body"))
}

private func meridianDef_Page_urgent(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("priority"), .string("p0"))
}

public enum Ingest {

// MARK: - Domain types

public enum BrainUpgradeMode: String, Hashable, Codable, Sendable {
    case off, auto, notify
}

public enum JobState: String, Hashable, Codable, Sendable {
    case queued, running, succeeded, failed, cancelled, paused
}

public enum PageEnrichmentTier: String, Hashable, Codable, Sendable {
    case tier1, tier2, tier3
}

public enum PagePriority: String, Hashable, Codable, Sendable {
    case p0, p1, p2, p3
}

public enum QueryMode: String, Hashable, Codable, Sendable {
    case fast, deep, exhaustive
}

public enum SignalTier: String, Hashable, Codable, Sendable {
    case tier1, tier2, tier3
}

public enum VerdictStatus: String, Hashable, Codable, Sendable {
    case verified, partial, unverifiable, misattributed, retracted
}

public protocol PageKind: MeridianThing {
    var title: String { get }
    var slug: String { get }
    var body: String { get }
    var author: String { get }
    var priority: PagePriority { get }
    var enrichmentTier: PageEnrichmentTier { get }
}

public struct Page: PageKind {
    public var id: String
    public var title: String
    public var slug: String
    public var body: String
    public var author: String
    public var priority: PagePriority
    public var enrichmentTier: PageEnrichmentTier

    public init(
        id: String = "",
        title: String = "",
        slug: String = "",
        body: String = "",
        author: String = "",
        priority: PagePriority = .p0,
        enrichmentTier: PageEnrichmentTier = .tier1
    ) {
        self.id = id
        self.title = title
        self.slug = slug
        self.body = body
        self.author = author
        self.priority = priority
        self.enrichmentTier = enrichmentTier
    }
}

public protocol PersonKind: MeridianThing {
    var name: String { get }
    var headline: String { get }
    var email: String { get }
    var company: String { get }
}

public struct Person: PersonKind {
    public var id: String
    public var name: String
    public var headline: String
    public var email: String
    public var company: String

    public init(
        id: String = "",
        name: String = "",
        headline: String = "",
        email: String = "",
        company: String = ""
    ) {
        self.id = id
        self.name = name
        self.headline = headline
        self.email = email
        self.company = company
    }
}

public protocol CompanyKind: MeridianThing {
    var name: String { get }
    var domain: String { get }
    var description: String { get }
}

public struct Company: CompanyKind {
    public var id: String
    public var name: String
    public var domain: String
    public var description: String

    public init(
        id: String = "",
        name: String = "",
        domain: String = "",
        description: String = ""
    ) {
        self.id = id
        self.name = name
        self.domain = domain
        self.description = description
    }
}

public protocol MeetingKind: MeridianEvent {
    var title: String { get }
    var date: String { get }
    var transcript: String { get }
}

public struct Meeting: MeetingKind {
    public var id: String
    public var title: String
    public var date: String
    public var transcript: String

    public init(
        id: String = "",
        title: String = "",
        date: String = "",
        transcript: String = ""
    ) {
        self.id = id
        self.title = title
        self.date = date
        self.transcript = transcript
    }
}

public struct Concept: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Idea: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Original: MeridianArtifact {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Deal: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Link: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Source: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct TimelineEntry: MeridianEvent {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol ReportKind: MeridianArtifact {
    var title: String { get }
    var body: String { get }
}

public struct Report: ReportKind {
    public var id: String
    public var title: String
    public var body: String

    public init(
        id: String = "",
        title: String = "",
        body: String = ""
    ) {
        self.id = id
        self.title = title
        self.body = body
    }
}

public protocol JobKind: MeridianProcess {
    var status: String { get }
    var state: JobState { get }
}

public struct Job: JobKind {
    public var id: String
    public var status: String
    public var state: JobState

    public init(
        id: String = "",
        status: String = "",
        state: JobState = .queued
    ) {
        self.id = id
        self.status = status
        self.state = state
    }
}

public struct Task: MeridianProcess {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol SignalKind: MeridianSignal {
    var name: String { get }
    var phrasing: String { get }
    var tier: SignalTier { get }
}

public struct Signal: SignalKind {
    public var id: String
    public var name: String
    public var phrasing: String
    public var tier: SignalTier

    public init(
        id: String = "",
        name: String = "",
        phrasing: String = "",
        tier: SignalTier = .tier1
    ) {
        self.id = id
        self.name = name
        self.phrasing = phrasing
        self.tier = tier
    }
}

public struct Transcript: MeridianArtifact {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct WebhookEvent: MeridianEvent {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct SchemaPack: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Recipe: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol VerdictKind: MeridianVerdict {
    var status: VerdictStatus { get }
}

public struct Verdict: VerdictKind {
    public var id: String
    public var status: VerdictStatus

    public init(
        id: String = "",
        status: VerdictStatus = .verified
    ) {
        self.id = id
        self.status = status
    }
}

public protocol QueryKind: MeridianThing {
    var mode: QueryMode { get }
}

public struct Query: QueryKind {
    public var id: String
    public var mode: QueryMode

    public init(
        id: String = "",
        mode: QueryMode = .fast
    ) {
        self.id = id
        self.mode = mode
    }
}

public protocol BrainKind: MeridianSystem {
    var upgradeMode: BrainUpgradeMode { get }
}

public struct Brain: BrainKind {
    public var id: String
    public var upgradeMode: BrainUpgradeMode

    public init(
        id: String = "",
        upgradeMode: BrainUpgradeMode = .off
    ) {
        self.id = id
        self.upgradeMode = upgradeMode
    }
}

public protocol EntityKind: MeridianThing {
    var name: String { get }
    var type: String { get }
}

public struct Entity: EntityKind {
    public var id: String
    public var name: String
    public var type: String

    public init(
        id: String = "",
        name: String = "",
        type: String = ""
    ) {
        self.id = id
        self.name = name
        self.type = type
    }
}

public struct Attendee: PersonKind {
    public var id: String
    public var name: String
    public var headline: String
    public var email: String
    public var company: String

    public init(
        id: String = "",
        name: String = "",
        headline: String = "",
        email: String = "",
        company: String = ""
    ) {
        self.id = id
        self.name = name
        self.headline = headline
        self.email = email
        self.company = company
    }
}

public struct Input: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}


public struct Constants: Sendable {
    public let defaultEnrichmentTier: String = "tier2"
    public let defaultPriority: String = "p2"
    public let notabilityThreshold: Decimal = Decimal(20)
    public let enrichmentWindowInDays: Decimal = Decimal(7)
}

private static let constants = Constants()

public struct IngestInput: MeridianWorkflow {
    public let runtime: Runtime
    public let input: Input

    public static let skillMetadata: [String: String] = [
        "name": "ingest",
        "description": "Route content to specialized ingestion skills. Detects input type and delegates.",
        "triggers": "\"ingest this\"\n\"save this to brain\"\n\"process this meeting\"",
        "tools": "search\nget_page\nput_page\nadd_link\nadd_timeline_entry\nsync_brain",
        "mutating": "true",
        "writes_pages": "true",
        "writes_to": "people/\ncompanies/\nconcepts/\nmeetings/\nsources/",
    ]

    public init(runtime: Runtime, input: Input) {
        self.runtime = runtime
        self.input = input
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        state.bind("input", input)
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "IngestInput", parameters: [:])

        // L54
        let __meridianProseResults_L54 = try await runtime.executeProsePlan(
            prose: "ingest the source and update the brain\nParse the source to extract people, companies, dates, and events\nFor each entity mentioned, read its page and update compiled truth, or create a new page after the notability gate\nAppend a timeline entry for each event with date, summary, and source citation\nCreate cross-reference links for every entity pair mentioned together\nBack-link every mentioned entity's page to this page, and merge the event onto each entity's timeline",
            snapshot: state.snapshot(),
            scopedTools: ["link.add", "page.get", "page.search", "publish", "shell.run", "timeline.add"]
        )
        for (__key, __value) in __meridianProseResults_L54 {
            state.bind(__key, __value)
        }
        // L68
        let __meridianProseResults_L68 = try await runtime.executeProsePlan(
            prose: "detect and file entities on every message\nScan the message for mentions of people, companies, concepts, and original thinking\nFor each entity, search the brain; load and update an existing page, or create a new page after the notability gate\nDetect and enrich alongside the response so the conversation is never blocked",
            snapshot: state.snapshot(),
            scopedTools: ["link.add", "page.get", "page.search", "publish", "shell.run", "timeline.add"]
        )
        for (__key, __value) in __meridianProseResults_L68 {
            state.bind(__key, __value)
        }
        if __meridianShouldRun("progress:0.2:L73:C0") {
            // L73
            _ = try await runtime.invoke(
                tool: "shell.run",
                args: [
                    "command": .string("gbrain sync --no-pull --no-embed"),
                ]
            )

            try await runtime.checkpoint(label: "progress:0.2:L73:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenIngestthisFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenIngestthisFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("ingestThis", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.ingestThis.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("ingest this"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenSavethisbrainFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenSavethisbrainFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("saveThisBrain", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.saveThisBrain.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("save this to brain"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenProcessthismeetingFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenProcessthismeetingFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("processThisMeeting", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.processThisMeeting.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("process this meeting"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

}