// THIS FILE IS GENERATED BY MERIDIAN. DO NOT EDIT.
// Source: minion_orchestrator.meri
// Meridian IR version: 1.0

import Foundation
import MeridianRuntime

// B7: Runtime helper for {{ expr }} interpolation in fenced code blocks.
private func meridianStringify(_ v: Value) -> String {
    switch v {
    case .string(let s): return s
    case .number(let n): return "\(n)"
    case .boolean(let b): return b ? "true" : "false"
    case .null: return ""
    default: return v.description
    }
}

// 1B: Shell-escape a value for safe interpolation inside a double-
// quoted span of a shell command (escapes \\, ", $, and backtick).
private func meridianShellQuote(_ v: Value) -> String {
    var out = ""
    for ch in meridianStringify(v) {
        if ch == "\\" || ch == "\"" || ch == "$" || ch == "`" { out.append("\\") }
        out.append(ch)
    }
    return out
}

// 1D: Output invariant — true iff the value's string form matches the
// regex pattern (anchored anywhere). An invalid pattern fails closed.
private func meridianRegexMatches(_ v: Value?, _ pattern: String) -> Bool {
    let s = v.map(meridianStringify) ?? ""
    guard let re = try? NSRegularExpression(pattern: pattern) else { return false }
    return re.firstMatch(in: s, range: NSRange(s.startIndex..., in: s)) != nil
}

private func meridianDef_Job_broken(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("state"), .string("failed"))
}

private func meridianDef_Job_finished(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("state"), .string("succeeded"))
}

private func meridianDef_Page_unwritten(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.isEmpty(__subject.member("body"))
}

private func meridianDef_Page_urgent(_ __subjectValue: Value?) -> Bool {
    let __subject = __subjectValue ?? .null
    return MeridianComparison.eq(__subject.member("priority"), .string("p0"))
}

public enum MinionOrchestrator {

// MARK: - Domain types

public enum BrainUpgradeMode: String, Hashable, Codable, Sendable {
    case off, auto, notify
}

public enum JobState: String, Hashable, Codable, Sendable {
    case queued, running, succeeded, failed, cancelled, paused
}

public enum PageEnrichmentTier: String, Hashable, Codable, Sendable {
    case tier1, tier2, tier3
}

public enum PagePriority: String, Hashable, Codable, Sendable {
    case p0, p1, p2, p3
}

public enum QueryMode: String, Hashable, Codable, Sendable {
    case fast, deep, exhaustive
}

public enum SignalTier: String, Hashable, Codable, Sendable {
    case tier1, tier2, tier3
}

public enum VerdictStatus: String, Hashable, Codable, Sendable {
    case verified, partial, unverifiable, misattributed, retracted
}

public protocol PageKind: MeridianThing {
    var title: String { get }
    var slug: String { get }
    var body: String { get }
    var author: String { get }
    var priority: PagePriority { get }
    var enrichmentTier: PageEnrichmentTier { get }
}

public struct Page: PageKind {
    public var id: String
    public var title: String
    public var slug: String
    public var body: String
    public var author: String
    public var priority: PagePriority
    public var enrichmentTier: PageEnrichmentTier

    public init(
        id: String = "",
        title: String = "",
        slug: String = "",
        body: String = "",
        author: String = "",
        priority: PagePriority = .p0,
        enrichmentTier: PageEnrichmentTier = .tier1
    ) {
        self.id = id
        self.title = title
        self.slug = slug
        self.body = body
        self.author = author
        self.priority = priority
        self.enrichmentTier = enrichmentTier
    }
}

public protocol PersonKind: MeridianThing {
    var name: String { get }
    var headline: String { get }
    var email: String { get }
    var company: String { get }
}

public struct Person: PersonKind {
    public var id: String
    public var name: String
    public var headline: String
    public var email: String
    public var company: String

    public init(
        id: String = "",
        name: String = "",
        headline: String = "",
        email: String = "",
        company: String = ""
    ) {
        self.id = id
        self.name = name
        self.headline = headline
        self.email = email
        self.company = company
    }
}

public protocol CompanyKind: MeridianThing {
    var name: String { get }
    var domain: String { get }
    var description: String { get }
}

public struct Company: CompanyKind {
    public var id: String
    public var name: String
    public var domain: String
    public var description: String

    public init(
        id: String = "",
        name: String = "",
        domain: String = "",
        description: String = ""
    ) {
        self.id = id
        self.name = name
        self.domain = domain
        self.description = description
    }
}

public protocol MeetingKind: MeridianEvent {
    var title: String { get }
    var date: String { get }
    var transcript: String { get }
}

public struct Meeting: MeetingKind {
    public var id: String
    public var title: String
    public var date: String
    public var transcript: String

    public init(
        id: String = "",
        title: String = "",
        date: String = "",
        transcript: String = ""
    ) {
        self.id = id
        self.title = title
        self.date = date
        self.transcript = transcript
    }
}

public struct Concept: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Idea: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Original: MeridianArtifact {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Deal: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Link: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Source: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct TimelineEntry: MeridianEvent {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol ReportKind: MeridianArtifact {
    var title: String { get }
    var body: String { get }
}

public struct Report: ReportKind {
    public var id: String
    public var title: String
    public var body: String

    public init(
        id: String = "",
        title: String = "",
        body: String = ""
    ) {
        self.id = id
        self.title = title
        self.body = body
    }
}

public protocol JobKind: MeridianProcess {
    var status: String { get }
    var state: JobState { get }
}

public struct Job: JobKind {
    public var id: String
    public var status: String
    public var state: JobState

    public init(
        id: String = "",
        status: String = "",
        state: JobState = .queued
    ) {
        self.id = id
        self.status = status
        self.state = state
    }
}

public struct Task: MeridianProcess {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol SignalKind: MeridianSignal {
    var name: String { get }
    var phrasing: String { get }
    var tier: SignalTier { get }
}

public struct Signal: SignalKind {
    public var id: String
    public var name: String
    public var phrasing: String
    public var tier: SignalTier

    public init(
        id: String = "",
        name: String = "",
        phrasing: String = "",
        tier: SignalTier = .tier1
    ) {
        self.id = id
        self.name = name
        self.phrasing = phrasing
        self.tier = tier
    }
}

public struct Transcript: MeridianArtifact {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct WebhookEvent: MeridianEvent {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct SchemaPack: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Recipe: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public protocol VerdictKind: MeridianVerdict {
    var status: VerdictStatus { get }
}

public struct Verdict: VerdictKind {
    public var id: String
    public var status: VerdictStatus

    public init(
        id: String = "",
        status: VerdictStatus = .verified
    ) {
        self.id = id
        self.status = status
    }
}

public protocol QueryKind: MeridianThing {
    var mode: QueryMode { get }
}

public struct Query: QueryKind {
    public var id: String
    public var mode: QueryMode

    public init(
        id: String = "",
        mode: QueryMode = .fast
    ) {
        self.id = id
        self.mode = mode
    }
}

public protocol BrainKind: MeridianSystem {
    var upgradeMode: BrainUpgradeMode { get }
}

public struct Brain: BrainKind {
    public var id: String
    public var upgradeMode: BrainUpgradeMode

    public init(
        id: String = "",
        upgradeMode: BrainUpgradeMode = .off
    ) {
        self.id = id
        self.upgradeMode = upgradeMode
    }
}

public protocol EntityKind: MeridianThing {
    var name: String { get }
    var type: String { get }
}

public struct Entity: EntityKind {
    public var id: String
    public var name: String
    public var type: String

    public init(
        id: String = "",
        name: String = "",
        type: String = ""
    ) {
        self.id = id
        self.name = name
        self.type = type
    }
}

public struct Attendee: PersonKind {
    public var id: String
    public var name: String
    public var headline: String
    public var email: String
    public var company: String

    public init(
        id: String = "",
        name: String = "",
        headline: String = "",
        email: String = "",
        company: String = ""
    ) {
        self.id = id
        self.name = name
        self.headline = headline
        self.email = email
        self.company = company
    }
}

public struct Input: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}


public struct Constants: Sendable {
    public let defaultEnrichmentTier: String = "tier2"
    public let defaultPriority: String = "p2"
    public let notabilityThreshold: Decimal = Decimal(20)
    public let enrichmentWindowInDays: Decimal = Decimal(7)
}

private static let constants = Constants()

public struct MinionOrchestratorInput: MeridianWorkflow {
    public let runtime: Runtime
    public let input: Input

    public static let skillMetadata: [String: String] = [
        "name": "minion-orchestrator",
        "version": "1.0.0",
        "description": "Unified Minions skill for both deterministic shell jobs and LLM subagent\norchestration. Replaces the older `gbrain-jobs` routing intent. Use when:\nsubmitting gbrain jobs, shell/background tasks, spawning subagents,\nchecking progress, steering running work, pausing/resuming, parallel\nfan-out. One durable, observable, steerable queue interface.",
        "triggers": "\"gbrain jobs submit\"\n\"submit a gbrain job\"\n\"submit a shell job\"\n\"shell job\"\n\"run shell command in background\"\n\"deterministic background task\"\n\"spawn agent\"\n\"background task\"\n\"run in background\"\n\"check on agent\"\n\"agent progress\"\n\"what's running\"\n\"steer agent\"\n\"change direction\"\n\"tell the agent\"\n\"pause agent\"\n\"stop agent\"\n\"resume agent\"\n\"parallel tasks\"\n\"fan out\"\n\"do these in parallel\"",
        "tools": "submit_job\nget_job\nlist_jobs\ncancel_job\npause_job\nresume_job\nreplay_job\nsend_job_message\nget_job_progress",
        "mutating": "true",
    ]

    public init(runtime: Runtime, input: Input) {
        self.runtime = runtime
        self.input = input
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        state.bind("input", input)
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "MinionOrchestratorInput", parameters: [:])


        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenGbrainjobssubmitFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenGbrainjobssubmitFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("gbrainJobsSubmit", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.gbrainJobsSubmit.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("gbrain jobs submit"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenSubmitgbrainjobFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenSubmitgbrainjobFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("submitGbrainJob", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.submitGbrainJob.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("submit a gbrain job"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenSubmitshelljobFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenSubmitshelljobFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("submitShellJob", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.submitShellJob.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("submit a shell job"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenShelljobFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenShelljobFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("shellJob", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.shellJob.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("shell job"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenRunshellcommandinbackgroundFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenRunshellcommandinbackgroundFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("runShellCommandInBackground", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.runShellCommandInBackground.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("run shell command in background"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenDeterministicbackgroundtaskFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenDeterministicbackgroundtaskFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("deterministicBackgroundTask", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.deterministicBackgroundTask.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("deterministic background task"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenSpawnagentFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenSpawnagentFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("spawnAgent", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.spawnAgent.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("spawn agent"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenBackgroundtaskFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenBackgroundtaskFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("backgroundTask", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.backgroundTask.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("background task"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenRuninbackgroundFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenRuninbackgroundFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("runInBackground", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.runInBackground.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("run in background"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenCheckagentFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenCheckagentFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("checkAgent", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.checkAgent.fired",
                payload: [
                    "kind": .string("event"),
                    "spec": .string("check on agent"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenAgentprogressFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenAgentprogressFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("agentProgress", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.agentProgress.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("agent progress"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenWhatsrunningFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenWhatsrunningFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("whatSRunning", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.whatSRunning.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("what's running"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenSteeragentFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenSteeragentFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("steerAgent", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.steerAgent.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("steer agent"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenChangedirectionFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenChangedirectionFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("changeDirection", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.changeDirection.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("change direction"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenTellagentFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenTellagentFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("tellAgent", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.tellAgent.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("tell the agent"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenPauseagentFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenPauseagentFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("pauseAgent", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.pauseAgent.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("pause agent"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenStopagentFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenStopagentFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("stopAgent", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.stopAgent.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("stop agent"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenResumeagentFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenResumeagentFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("resumeAgent", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.resumeAgent.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("resume agent"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenParalleltasksFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenParalleltasksFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("parallelTasks", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.parallelTasks.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("parallel tasks"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenFanoutFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenFanoutFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("fanOut", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.fanOut.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("fan out"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct WhenDotheseinparallelFires: MeridianWorkflow {
    public let runtime: Runtime

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        await runtime.workflowStarted(workflowName: "WhenDotheseinparallelFires", parameters: [:])

        if __meridianShouldRun("progress:0.0:L1:C0") {
            // L1
            try await runtime.wait(.event("doTheseInParallel", matching: nil))
            try await runtime.checkpoint(label: "progress:0.0:L1:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L1:C0") {
            // L1
            try await runtime.emit(
                event: "trigger.doTheseInParallel.fired",
                payload: [
                    "kind": .string("keyword"),
                    "spec": .string("do these in parallel"),
                ]
            )
            try await runtime.checkpoint(label: "progress:0.1:L1:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

}