// THIS FILE IS GENERATED BY MERIDIAN. DO NOT EDIT.
// Source: domain.meri
// Meridian IR version: 1.0

import Foundation
import MeridianRuntime

// B7: Runtime helper for {{ expr }} interpolation in fenced code blocks.
private func meridianStringify(_ v: Value) -> String { v.scalarDescription }
private func meridianFormat(_ v: Value, as formatter: String) -> String {
    switch formatter.lowercased() {
    case "integer":
        if case .number(let n) = v { return NSDecimalNumber(decimal: n).intValue.description }
    case let f where f.hasPrefix("decimal(") && f.hasSuffix(")"):
        if case .number(let n) = v, let places = Int(f.dropFirst("decimal(".count).dropLast()) {
            let nf = NumberFormatter(); nf.minimumFractionDigits = places; nf.maximumFractionDigits = places
            return nf.string(from: NSDecimalNumber(decimal: n)) ?? n.description
        }
    case "short date", "long date":
        if case .date(let d) = v {
            let df = DateFormatter(); df.dateStyle = formatter.lowercased() == "short date" ? .short : .long; df.timeStyle = .none
            return df.string(from: d)
        }
    default: break
    }
    return meridianStringify(v)
}

// 1B: Shell-escape a value for safe interpolation inside a double-
// quoted span of a shell command (escapes \\, ", $, and backtick).
private func meridianShellQuote(_ v: Value) -> String {
    var out = ""
    for ch in meridianStringify(v) {
        if ch == "\\" || ch == "\"" || ch == "$" || ch == "`" { out.append("\\") }
        out.append(ch)
    }
    return out
}

// 1D: Output invariant — true iff the value's string form matches the
// regex pattern (anchored anywhere). An invalid pattern fails closed.
private func meridianRegexMatches(_ v: Value?, _ pattern: String) -> Bool {
    let s = v.map(meridianStringify) ?? ""
    guard let re = try? NSRegularExpression(pattern: pattern) else { return false }
    return re.firstMatch(in: s, range: NSRange(s.startIndex..., in: s)) != nil
}

// MARK: - Domain types

public enum PageLifecycle: String, Hashable, Codable, Sendable {
    case draft, published
}

public protocol PageKind: MeridianThing {
    var title: String { get }
    var lifecycle: PageLifecycle { get }
}

public struct Page: PageKind {
    public var id: String
    public var title: String
    public var lifecycle: PageLifecycle

    public init(
        id: String = "",
        title: String = "",
        lifecycle: PageLifecycle = .draft
    ) {
        self.id = id
        self.title = title
        self.lifecycle = lifecycle
    }
}


public struct DomainTableReport: MeridianWorkflow {
    public let runtime: Runtime

    public static let skillMetadata: [String: String] = [
        "name": "domain table report",
        "vocabulary": "domain.merconfig",
    ]

    public init(runtime: Runtime) {
        self.runtime = runtime
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        await runtime.workflowStarted(workflowName: "DomainTableReport", parameters: [:])

        state.bind("table", Value.list([.record(["triggerPhrase": .string("daily briefing"), "skill": .string("briefing"), "score": .number(Decimal(10))]), .record(["triggerPhrase": .string("maintenance sweep"), "skill": .string("maintain"), "score": .number(Decimal(20))])]))
        state.bind("chosenSkill", try ({ () throws -> Value? in guard let __rows = state.get("table")?.asList else { throw ToolError.implementation(code: "table.lookup_miss", message: "table table is not bound", cause: nil) }; for __row in __rows { if MeridianComparison.eq(__row.member("triggerPhrase"), .string("daily briefing")) { return __row.member("skill") } }; throw ToolError.implementation(code: "table.lookup_miss", message: "no row in table where triggerPhrase matches", cause: nil) })())
        state.bind("reportBody", ("[date]\n" + ({ () -> String in var __out = ""; for __item in ((state.get("table"))?.asList ?? []) { __out += "- " + meridianStringify(__item.member("skill") ?? .null) + ": " + meridianFormat(__item.member("score") ?? .null, as: "integer") + "\n" }; return __out })() + "\n" + ({ () -> String in if MeridianComparison.eq(state.get("chosenSkill"), state.get("briefing")) { return "chosen briefing" } else { return "chosen another skill" } })()))
        if __meridianShouldRun("progress:0.3:L27:C0") {
            try await runtime.emit(
                event: "domain.report",
                payload: [
                    "body": state.get("reportBody") ?? .null,
                ]
            )
            try await runtime.checkpoint(label: "progress:0.3:L27:C0", state: state.snapshot())
        }
        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}
