// THIS FILE IS GENERATED BY MERIDIAN. DO NOT EDIT.
// Source: incident_response.meridian
// Meridian IR version: 1.0

import Foundation
import MeridianRuntime

// B7: Runtime helper for {{ expr }} interpolation in fenced code blocks.
private func meridianStringify(_ v: Value) -> String {
    switch v {
    case .string(let s): return s
    case .number(let n): return "\(n)"
    case .boolean(let b): return b ? "true" : "false"
    case .null: return ""
    default: return v.description
    }
}

// 1B: Shell-escape a value for safe interpolation inside a double-
// quoted span of a shell command (escapes \\, ", $, and backtick).
private func meridianShellQuote(_ v: Value) -> String {
    var out = ""
    for ch in meridianStringify(v) {
        if ch == "\\" || ch == "\"" || ch == "$" || ch == "`" { out.append("\\") }
        out.append(ch)
    }
    return out
}

// 1D: Output invariant — true iff the value's string form matches the
// regex pattern (anchored anywhere). An invalid pattern fails closed.
private func meridianRegexMatches(_ v: Value?, _ pattern: String) -> Bool {
    let s = v.map(meridianStringify) ?? ""
    guard let re = try? NSRegularExpression(pattern: pattern) else { return false }
    return re.firstMatch(in: s, range: NSRange(s.startIndex..., in: s)) != nil
}

// MARK: - Domain types

public struct PullRequest: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Comment: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct CiRun: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Check: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}


public struct IncidentResponsePullRequest: MeridianWorkflow {
    public let runtime: Runtime
    public let pullRequest: PullRequest

    public static let skillMetadata: [String: String] = [
        "name": "incident response",
        "description": "Coordinate incident checks with strict tool execution.",
        "goal": "Triage the incident and produce bounded, auditable actions.",
        "parameters": "pull request",
        "vocabulary": "../github.merconfig",
    ]

    public init(runtime: Runtime, pullRequest: PullRequest) {
        self.runtime = runtime
        self.pullRequest = pullRequest
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        state.bind("pullRequest", pullRequest)
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        await runtime.workflowStarted(workflowName: "IncidentResponsePullRequest", parameters: [:])

        if __meridianShouldRun("progress:0.0:L10:C0") {
            let ciStatus = try await runtime.invoke(
                tool: "getCIStatus",
                args: [
                    "pr": state.get("pullRequest.number") ?? .null,
                ]
            )
            state.bind("ciStatus", ciStatus)

            try await runtime.checkpoint(label: "progress:0.0:L10:C0", state: state.snapshot())
        }
        if try await runtime.discretion.decide(DiscretionContext(question: "the incident is severe", snapshot: state.snapshot())) {
            if __meridianShouldRun("progress:0.1.then.0:L12:C0") {
                let fix = try await runtime.invoke(
                    tool: "commitFix",
                    args: [
                        "message": .string("start incident mitigation"),
                    ]
                )
                state.bind("fix", fix)

                try await runtime.checkpoint(label: "progress:0.1.then.0:L12:C0", state: state.snapshot())
            }
        }


        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct CoordinateIncidentResponse: MeridianWorkflow {
    public let runtime: Runtime
    public let pullRequest: PullRequest

    public init(runtime: Runtime, pullRequest: PullRequest) {
        self.runtime = runtime
        self.pullRequest = pullRequest
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        state.bind("pullRequest", pullRequest)
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        await runtime.workflowStarted(workflowName: "CoordinateIncidentResponse", parameters: [:])

        let __meridianProseResults_L15 = try await runtime.executeAutonomousLoop(
            prose: "Inspect the available signals, take one safe mitigation step, and stop once the active blocker is handled",
            snapshot: state.snapshot(),
            scopedTools: ["approvePR", "commitFix", "getCIStatus", "getConflicts", "listPRComments", "mergePR", "pushBranch", "requestChanges", "resolveComment", "syncBranch"],
            maxSteps: 32,
            replanAfterFailures: 1
        )
        for (__key, __value) in __meridianProseResults_L15 {
            state.bind(__key, __value)
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}
