// THIS FILE IS GENERATED BY MERIDIAN. DO NOT EDIT.
// Source: large_release_train.meridian
// Meridian IR version: 1.0

import Foundation
import MeridianRuntime

// B7: Runtime helper for {{ expr }} interpolation in fenced code blocks.
private func meridianStringify(_ v: Value) -> String {
    switch v {
    case .string(let s): return s
    case .number(let n): return "\(n)"
    case .boolean(let b): return b ? "true" : "false"
    case .null: return ""
    default: return v.description
    }
}

// 1B: Shell-escape a value for safe interpolation inside a double-
// quoted span of a shell command (escapes \\, ", $, and backtick).
private func meridianShellQuote(_ v: Value) -> String {
    var out = ""
    for ch in meridianStringify(v) {
        if ch == "\\" || ch == "\"" || ch == "$" || ch == "`" { out.append("\\") }
        out.append(ch)
    }
    return out
}

// 1D: Output invariant — true iff the value's string form matches the
// regex pattern (anchored anywhere). An invalid pattern fails closed.
private func meridianRegexMatches(_ v: Value?, _ pattern: String) -> Bool {
    let s = v.map(meridianStringify) ?? ""
    guard let re = try? NSRegularExpression(pattern: pattern) else { return false }
    return re.firstMatch(in: s, range: NSRange(s.startIndex..., in: s)) != nil
}

// MARK: - Domain types

public struct Repository: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct PullRequest: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct ReviewComment: MeridianMessage {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Reviewer: MeridianRole {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Commit: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct CiRun: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Check: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Deployment: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Release: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct RolloutStage: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Incident: MeridianProcess {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Vulnerability: MeridianFact {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Dependency: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct PolicyDecision: MeridianVerdict {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct RemediationTask: MeridianAction {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct AuditNote: MeridianEvent {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct CustomerTicket: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct CustomerProfile: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct SlaPolicy: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}


public struct Constants: Sendable {
    public let defaultReviewTimeout: Duration = Duration.seconds(1800)
    public let defaultCanaryPercent: Decimal = Decimal(5)
    public let defaultRolloutPercent: Decimal = Decimal(100)
    public let highRiskThreshold: Decimal = Decimal(0.7)
    public let blockerSeverityThreshold: String = "high"
    public let maximumReplanAttempts: Decimal = Decimal(3)
    public let maximumLoopSteps: Decimal = Decimal(12)
    public let vipTierLabel: String = "vip"
}

private let constants = Constants()

public struct Instances: Sendable {
    public let enterpriseSla: Value = .record([
        "name": .string("Enterprise"),
        "responseMinutes": .number(Decimal(15)),
        "resolutionHours": .number(Decimal(4)),
    ])
    public let standardSla: Value = .record([
        "name": .string("Standard"),
        "responseMinutes": .number(Decimal(60)),
        "resolutionHours": .number(Decimal(24)),
    ])
}

private let instances = Instances()

public struct LargeReleaseTrainPullRequest: MeridianWorkflow {
    public let runtime: Runtime
    public let pullRequest: PullRequest

    public static let skillMetadata: [String: String] = [
        "name": "large release train",
        "description": "Coordinate a multi-stage release with a deterministic outer gate that delegates planning to discretion mode and risky stabilisation to a bounded autonomy loop.",
        "goal": "Promote a release through staged rollout while keeping all risky decisions auditable.",
        "parameters": "pull request",
        "vocabulary": "comprehensive_workflows.merconfig",
    ]

    public init(runtime: Runtime, pullRequest: PullRequest) {
        self.runtime = runtime
        self.pullRequest = pullRequest
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        state.bind("pullRequest", pullRequest)
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        let instances = Instances()
        await runtime.workflowStarted(workflowName: "LargeReleaseTrainPullRequest", parameters: [:])

        if __meridianShouldRun("progress:0.0:L168:C0") {
            try await runtime.emit(
                event: "audit.opened",
                payload: [
                    "pr": state.get("pullRequest.number") ?? .null,
                ]
            )
            try await runtime.checkpoint(label: "progress:0.0:L168:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L162:C0") {
            let ciStatus = try await runtime.invoke(
                tool: "getCiStatus",
                args: [
                    "pr": state.get("pullRequest.number") ?? .null,
                ]
            )
            state.bind("ciStatus", ciStatus)

            try await runtime.checkpoint(label: "progress:0.1:L162:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.2:L12:C0") {
            let mergeStatus = try await runtime.invoke(
                tool: "getMergeStatus",
                args: [
                    "pr": state.get("pullRequest.number") ?? .null,
                ]
            )
            state.bind("mergeStatus", mergeStatus)

            try await runtime.checkpoint(label: "progress:0.2:L12:C0", state: state.snapshot())
        }
        if MeridianComparison.eq(state.get("ciStatus"), state.get("failed")) {
            if __meridianShouldRun("progress:0.3.then.0:L174:C0") {
                try await runtime.emit(
                    event: "audit.note",
                    payload: [
                        "pr": state.get("pullRequest.number") ?? .null,
                        "reason": .string("ci failed before release"),
                    ]
                )
                try await runtime.checkpoint(label: "progress:0.3.then.0:L174:C0", state: state.snapshot())
            }
            await runtime.complete(reason: "ci_blocked")
            return WorkflowResult(reason: "ci_blocked", durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
        }

        if MeridianComparison.eq(state.get("mergeStatus"), state.get("conflicting")) {
            if __meridianShouldRun("progress:0.4.then.0:L174:C0") {
                try await runtime.emit(
                    event: "audit.note",
                    payload: [
                        "pr": state.get("pullRequest.number") ?? .null,
                        "reason": .string("merge conflicts before release"),
                    ]
                )
                try await runtime.checkpoint(label: "progress:0.4.then.0:L174:C0", state: state.snapshot())
            }
            await runtime.complete(reason: "merge_conflicts")
            return WorkflowResult(reason: "merge_conflicts", durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
        }

        if __meridianShouldRun("progress:0.5:L22:C0") {
            _ = try await PlanReleaseRollout(runtime: runtime, pullRequest: pullRequest).run()
            try await runtime.checkpoint(label: "progress:0.5:L22:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.6:L26:C0") {
            _ = try await AutonomouslyStabilizeRelease(runtime: runtime, pullRequest: pullRequest).run()
            try await runtime.checkpoint(label: "progress:0.6:L26:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.7:L171:C0") {
            try await runtime.emit(
                event: "audit.closed",
                payload: [
                    "pr": state.get("pullRequest.number") ?? .null,
                ]
            )
            try await runtime.checkpoint(label: "progress:0.7:L171:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct PlanReleaseRollout: MeridianWorkflow {
    public let runtime: Runtime
    public let pullRequest: PullRequest

    public init(runtime: Runtime, pullRequest: PullRequest) {
        self.runtime = runtime
        self.pullRequest = pullRequest
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        state.bind("pullRequest", pullRequest)
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        let instances = Instances()
        await runtime.workflowStarted(workflowName: "PlanReleaseRollout", parameters: [:])

        let __meridianProseResults_L35 = try await runtime.executeProsePlan(
            prose: "Read the failing jobs, deployment health, and merge status. Propose only promote deployment, rollback deployment, halt release, and notify channel actions. Never modify code or push branches from this plan",
            snapshot: state.snapshot(),
            scopedTools: ["applySmallestRepair", "draftSupportReply", "escalateCustomerTicket", "evaluatePolicy", "getCIStatus", "getDeploymentHealth", "getFailingJobs", "getMergeStatus", "getPullRequest", "haltRelease", "listOutdatedDependencies", "listPullRequestComments", "mitigateService", "notifyChannel", "openIncident", "openRemediationTask", "pageOncall", "promoteDeployment", "pushBranch", "readCustomerProfile", "readCustomerTicket", "recordAuditNote", "requestReviewerApproval", "resolveComment", "rollbackDeployment", "runTestSuite", "scanVulnerabilities", "sendSupportReply", "snapshotServiceHealth", "syncBranch", "updateIncident", "updateRemediationTask", "upgradeDependency"]
        )
        for (__key, __value) in __meridianProseResults_L35 {
            state.bind(__key, __value)
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct AutonomouslyStabilizeRelease: MeridianWorkflow {
    public let runtime: Runtime
    public let pullRequest: PullRequest

    public init(runtime: Runtime, pullRequest: PullRequest) {
        self.runtime = runtime
        self.pullRequest = pullRequest
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        state.bind("pullRequest", pullRequest)
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        let instances = Instances()
        await runtime.workflowStarted(workflowName: "AutonomouslyStabilizeRelease", parameters: [:])

        let __meridianProseResults_L38 = try await runtime.executeAutonomousLoop(
            prose: "Watch the rolling deployment and CI signals. Take the single safest action (promote, rollback, or halt) and stop once the rollout is healthy",
            snapshot: state.snapshot(),
            scopedTools: ["applySmallestRepair", "draftSupportReply", "escalateCustomerTicket", "evaluatePolicy", "getCIStatus", "getDeploymentHealth", "getFailingJobs", "getMergeStatus", "getPullRequest", "haltRelease", "listOutdatedDependencies", "listPullRequestComments", "mitigateService", "notifyChannel", "openIncident", "openRemediationTask", "pageOncall", "promoteDeployment", "pushBranch", "readCustomerProfile", "readCustomerTicket", "recordAuditNote", "requestReviewerApproval", "resolveComment", "rollbackDeployment", "runTestSuite", "scanVulnerabilities", "sendSupportReply", "snapshotServiceHealth", "syncBranch", "updateIncident", "updateRemediationTask", "upgradeDependency"],
            maxSteps: 4,
            replanAfterFailures: 1,
            until: { __meridianAutonomySnapshot in
                var state = State()
                state.restore(from: __meridianAutonomySnapshot)
                return MeridianComparison.eq(state.get("ciStatus"), state.get("passed"))
            },
            unless: { __meridianAutonomySnapshot in
                var state = State()
                state.restore(from: __meridianAutonomySnapshot)
                return MeridianComparison.eq(state.get("mergeStatus"), state.get("conflicting"))
            }
        )
        for (__key, __value) in __meridianProseResults_L38 {
            state.bind(__key, __value)
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}
