// THIS FILE IS GENERATED BY MERIDIAN. DO NOT EDIT.
// Source: review_comment_refactor.meri
// Meridian IR version: 1.0

import Foundation
import MeridianRuntime

// B7: Runtime helper for {{ expr }} interpolation in fenced code blocks.
private func meridianStringify(_ v: Value) -> String { v.scalarDescription }

// 1B: Shell-escape a value for safe interpolation inside a double-
// quoted span of a shell command (escapes \\, ", $, and backtick).
private func meridianShellQuote(_ v: Value) -> String {
    var out = ""
    for ch in meridianStringify(v) {
        if ch == "\\" || ch == "\"" || ch == "$" || ch == "`" { out.append("\\") }
        out.append(ch)
    }
    return out
}

// 1D: Output invariant — true iff the value's string form matches the
// regex pattern (anchored anywhere). An invalid pattern fails closed.
private func meridianRegexMatches(_ v: Value?, _ pattern: String) -> Bool {
    let s = v.map(meridianStringify) ?? ""
    guard let re = try? NSRegularExpression(pattern: pattern) else { return false }
    return re.firstMatch(in: s, range: NSRange(s.startIndex..., in: s)) != nil
}

// MARK: - Domain types

public struct Repository: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct PullRequest: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct ReviewComment: MeridianMessage {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Reviewer: MeridianRole {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Commit: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct CiRun: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Check: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Deployment: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Release: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct RolloutStage: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Incident: MeridianProcess {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Vulnerability: MeridianFact {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct Dependency: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct PolicyDecision: MeridianVerdict {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct RemediationTask: MeridianAction {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct AuditNote: MeridianEvent {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct CustomerTicket: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct CustomerProfile: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}

public struct SlaPolicy: MeridianThing {
    public var id: String

    public init(
        id: String = ""
    ) {
        self.id = id
    }
}


public struct Constants: Sendable {
    public let defaultReviewTimeout: Duration = Duration.seconds(1800)
    public let defaultCanaryPercent: Decimal = Decimal(5)
    public let defaultRolloutPercent: Decimal = Decimal(100)
    public let highRiskThreshold: Decimal = Decimal(0.7)
    public let blockerSeverityThreshold: String = "high"
    public let maximumReplanAttempts: Decimal = Decimal(3)
    public let maximumLoopSteps: Decimal = Decimal(12)
    public let vipTierLabel: String = "vip"
}

private let constants = Constants()

public struct Instances: Sendable {
    public let enterpriseSla: Value = .record([
        "name": .string("Enterprise"),
        "responseMinutes": .number(Decimal(15)),
        "resolutionHours": .number(Decimal(4)),
    ])
    public let standardSla: Value = .record([
        "name": .string("Standard"),
        "responseMinutes": .number(Decimal(60)),
        "resolutionHours": .number(Decimal(24)),
    ])
}

private let instances = Instances()

public struct ReviewCommentRefactorPullRequest: MeridianWorkflow {
    public let runtime: Runtime
    public let pullRequest: PullRequest

    public static let skillMetadata: [String: String] = [
        "name": "review comment refactor",
        "description": "Walk a pull request's review comments and apply small refactor suggestions, demonstrating topic labels, implicit single-parameter phrase fill, and English idiom phrasing.",
        "goal": "Resolve obviously addressed comments while preserving an audit trail for the rest.",
        "parameters": "pull request",
        "vocabulary": "comprehensive_workflows.merconfig",
    ]

    public init(runtime: Runtime, pullRequest: PullRequest) {
        self.runtime = runtime
        self.pullRequest = pullRequest
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        state.bind("pullRequest", pullRequest)
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        let instances = Instances()
        await runtime.workflowStarted(workflowName: "ReviewCommentRefactorPullRequest", parameters: [:])

        if __meridianShouldRun("progress:0.0:L168:C0") {
            try await runtime.emit(
                event: "audit.opened",
                payload: [
                    "pr": state.get("pullRequest.number") ?? .null,
                ]
            )
            try await runtime.checkpoint(label: "progress:0.0:L168:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.1:L11:C0") {
            let comments = try await runtime.invoke(
                tool: "listPullRequestComments",
                args: [
                    "pr": state.get("pullRequest.number") ?? .null,
                ]
            )
            state.bind("comments", comments)

            try await runtime.checkpoint(label: "progress:0.1:L11:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.2:L162:C0") {
            let ciStatus = try await runtime.invoke(
                tool: "getCiStatus",
                args: [
                    "pr": state.get("pullRequest.number") ?? .null,
                ]
            )
            state.bind("ciStatus", ciStatus)

            try await runtime.checkpoint(label: "progress:0.2:L162:C0", state: state.snapshot())
        }
        if __meridianShouldRun("progress:0.3:L16:C0") {
            try await runtime.assert(MeridianComparison.eq(state.get("ciStatus"), state.get("passed")), message: "Expected the ci status is passed")
            try await runtime.checkpoint(label: "progress:0.3:L16:C0", state: state.snapshot())
        }
        for (__meridianLoopIndex_0_4, comment) in (state.get("comments")?.asList ?? []).enumerated() {
            let __meridianLoopLabel_0_4 = "progress:0.4:iteration:\(__meridianLoopIndex_0_4)"
            if __meridianShouldRun(__meridianLoopLabel_0_4) {
            state.bind("comment", comment)
                if __meridianShouldRun("progress:0.4.body.0:L20:C0") {
                    _ = try await ResolveComment(runtime: runtime, comment: (try Value.from(comment).coerce(to: Value.self))).run()
                    try await runtime.checkpoint(label: "progress:0.4.body.0:L20:C0", state: state.snapshot())
                }
                try await runtime.checkpoint(label: __meridianLoopLabel_0_4, state: state.snapshot())
            }
        }

        if __meridianShouldRun("progress:0.5:L171:C0") {
            try await runtime.emit(
                event: "audit.closed",
                payload: [
                    "pr": state.get("pullRequest.number") ?? .null,
                ]
            )
            try await runtime.checkpoint(label: "progress:0.5:L171:C0", state: state.snapshot())
        }

        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}

public struct ResolveComment: MeridianWorkflow {
    public let runtime: Runtime
    public let comment: Value

    public init(runtime: Runtime, comment: Value) {
        self.runtime = runtime
        self.comment = comment
    }

    public func run() async throws -> WorkflowResult {
        var state = State()
        state.bind("comment", comment)
        let __meridianResumeContext = await runtime.consumeResumeContext()
        if let __meridianResumeContext {
            state.restore(from: __meridianResumeContext.restoredState)
        }
        var __meridianResumeTarget = __meridianResumeContext?.lastCheckpointLabel
        func __meridianShouldRun(_ label: String) -> Bool {
            guard let target = __meridianResumeTarget else { return true }
            if target == label { __meridianResumeTarget = nil }
            return false
        }
        let constants = Constants()
        let instances = Instances()
        await runtime.workflowStarted(workflowName: "ResolveComment", parameters: [:])

        if try await runtime.discretion.decide(DiscretionContext(question: "the comment was already addressed", snapshot: state.snapshot())) {
            if __meridianShouldRun("progress:0.0.then.0:L30:C0") {
                let comment = try await runtime.invoke(
                    tool: "resolveComment",
                    args: [
                        "commentId": state.get("comment.id") ?? .null,
                    ]
                )
                state.bind("comment", comment)

                try await runtime.checkpoint(label: "progress:0.0.then.0:L30:C0", state: state.snapshot())
            }
        } else {
            if __meridianShouldRun("progress:0.0.else.0:L174:C0") {
                try await runtime.emit(
                    event: "audit.note",
                    payload: [
                        "pr": state.get("pullRequest.number") ?? .null,
                        "reason": .string("comment kept open after refactor pass"),
                    ]
                )
                try await runtime.checkpoint(label: "progress:0.0.else.0:L174:C0", state: state.snapshot())
            }
        }


        await runtime.complete(reason: nil)
        return WorkflowResult(reason: nil, durationMS: await runtime.elapsedMS(), eventCount: await runtime.eventCount(), bindings: state.snapshot().asValues)
    }
}
